`timescale 1ns / 1ps
// Generated by CIRCT firtool-1.128.0
module ram_32x32_s8_b65536 (
    input         clock,
    reset,
    RAM_write_en,
    input  [31:0] RAM_write_addr,
    RAM_write_data,
    input  [ 3:0] RAM_write_strb,
    output        RAM_write_resp,
    input         RAM_read_en,
    input  [31:0] RAM_read_addr,
    output [31:0] RAM_read_data,
    output        RAM_read_resp
);

  reg [31:0] ram_0;
  reg [31:0] ram_1;
  reg [31:0] ram_2;
  reg [31:0] ram_3;
  reg [31:0] ram_4;
  reg [31:0] ram_5;
  reg [31:0] ram_6;
  reg [31:0] ram_7;
  wire [31:0] _aw_offset_addr_T = RAM_write_addr - 32'h10000;
  wire [31:0] _ar_offset_addr_T = RAM_read_addr - 32'h10000;
  wire aw_valid = (|(RAM_write_addr[31:16])) & _aw_offset_addr_T < 32'h20;
  wire ar_valid = (|(RAM_read_addr[31:16])) & _ar_offset_addr_T < 32'h20;
  wire [2:0]  _mem_addr_T_3 =
    RAM_read_en ? _ar_offset_addr_T[4:2] : RAM_write_en ? _aw_offset_addr_T[4:2] : 3'h0;
  reg [31:0] casez_tmp;
  always_comb begin
    casez (_mem_addr_T_3)
      3'b000:  casez_tmp = ram_0;
      3'b001:  casez_tmp = ram_1;
      3'b010:  casez_tmp = ram_2;
      3'b011:  casez_tmp = ram_3;
      3'b100:  casez_tmp = ram_4;
      3'b101:  casez_tmp = ram_5;
      3'b110:  casez_tmp = ram_6;
      default: casez_tmp = ram_7;
    endcase
  end  // always_comb
  wire _GEN = RAM_write_en & aw_valid;
  wire [31:0] _ram_T_12 = {
    RAM_write_strb[3] ? RAM_write_data[31:24] : casez_tmp[31:24],
    RAM_write_strb[2] ? RAM_write_data[23:16] : casez_tmp[23:16],
    RAM_write_strb[1] ? RAM_write_data[15:8] : casez_tmp[15:8],
    RAM_write_strb[0] ? RAM_write_data[7:0] : casez_tmp[7:0]
  };
  always @(posedge clock) begin
    if (reset) begin
      ram_0 <= 32'h0;
      ram_1 <= 32'h0;
      ram_2 <= 32'h0;
      ram_3 <= 32'h0;
      ram_4 <= 32'h0;
      ram_5 <= 32'h0;
      ram_6 <= 32'h0;
      ram_7 <= 32'h0;
    end else begin
      if (_GEN & _mem_addr_T_3 == 3'h0) ram_0 <= _ram_T_12;
      if (_GEN & _mem_addr_T_3 == 3'h1) ram_1 <= _ram_T_12;
      if (_GEN & _mem_addr_T_3 == 3'h2) ram_2 <= _ram_T_12;
      if (_GEN & _mem_addr_T_3 == 3'h3) ram_3 <= _ram_T_12;
      if (_GEN & _mem_addr_T_3 == 3'h4) ram_4 <= _ram_T_12;
      if (_GEN & _mem_addr_T_3 == 3'h5) ram_5 <= _ram_T_12;
      if (_GEN & _mem_addr_T_3 == 3'h6) ram_6 <= _ram_T_12;
      if (_GEN & (&_mem_addr_T_3)) ram_7 <= _ram_T_12;
    end
  end  // always @(posedge)
  assign RAM_write_resp = aw_valid;
  assign RAM_read_data  = RAM_read_en & ar_valid ? casez_tmp : 32'h0;
  assign RAM_read_resp  = ar_valid;
endmodule

module axifull_slave_ram_32x32_i4_u1_s8_b65536 (
    input         clock,
    reset,
    input  [31:0] S_AXI_AWADDR,
    input  [ 2:0] S_AXI_AWPROT,
    input         S_AXI_AWVALID,
    output        S_AXI_AWREADY,
    input  [ 3:0] S_AXI_AWID,
    input  [ 7:0] S_AXI_AWLEN,
    input  [ 2:0] S_AXI_AWSIZE,
    input  [ 1:0] S_AXI_AWBURST,
    input         S_AXI_AWLOCK,
    input  [ 3:0] S_AXI_AWCACHE,
    S_AXI_AWQOS,
    S_AXI_AWREGION,
    input         S_AXI_AWUSER,
    input  [31:0] S_AXI_WDATA,
    input  [ 3:0] S_AXI_WSTRB,
    input         S_AXI_WVALID,
    output        S_AXI_WREADY,
    input         S_AXI_WLAST,
    input  [ 3:0] S_AXI_WID,
    input         S_AXI_WUSER,
    S_AXI_BREADY,
    output [ 1:0] S_AXI_BRESP,
    output        S_AXI_BVALID,
    output [ 3:0] S_AXI_BID,
    output        S_AXI_BUSER,
    input  [31:0] S_AXI_ARADDR,
    input  [ 2:0] S_AXI_ARPROT,
    input         S_AXI_ARVALID,
    output        S_AXI_ARREADY,
    input  [ 3:0] S_AXI_ARID,
    input  [ 7:0] S_AXI_ARLEN,
    input  [ 2:0] S_AXI_ARSIZE,
    input  [ 1:0] S_AXI_ARBURST,
    input         S_AXI_ARLOCK,
    input  [ 3:0] S_AXI_ARCACHE,
    S_AXI_ARQOS,
    S_AXI_ARREGION,
    input         S_AXI_ARUSER,
    S_AXI_RREADY,
    output [31:0] S_AXI_RDATA,
    output [ 1:0] S_AXI_RRESP,
    output        S_AXI_RVALID,
    S_AXI_RLAST,
    output [ 3:0] S_AXI_RID,
    output        S_AXI_RUSER
);

  wire        _mmap_region_RAM_write_resp;
  wire [31:0] _mmap_region_RAM_read_data;
  wire        _mmap_region_RAM_read_resp;
  reg         axi_awready;
  reg         axi_awv_awr_flag;
  reg  [31:0] axi_awaddr;
  reg  [ 1:0] axi_awburst;
  reg  [ 7:0] axi_awlen;
  reg  [ 7:0] axi_awlen_cntr;
  reg         axi_wready;
  reg         axi_bvalid;
  reg  [ 1:0] axi_bresp;
  reg         axi_arready;
  reg  [31:0] axi_araddr;
  reg  [ 1:0] axi_arburst;
  reg  [ 7:0] axi_arlen;
  reg  [ 7:0] axi_arlen_cntr;
  reg         axi_arv_arr_flag;
  reg         axi_rvalid;
  reg  [ 1:0] axi_rresp;
  reg         axi_rlast;
  reg  [31:0] casez_tmp;
  wire [31:0] _GEN = {22'h0, axi_awlen, 2'h0};
  always_comb begin
    casez (axi_awburst)
      2'b00: casez_tmp = axi_awaddr;
      2'b01: casez_tmp = {axi_awaddr[31:2] + 30'h1, 2'h0};
      2'b10:
      casez_tmp =
          {21'h0, axi_awaddr[10:0] & {1'h0, axi_awlen, 2'h0}} == _GEN
            ? axi_awaddr - _GEN
            : {axi_awaddr[31:2] + 30'h1, 2'h0};
      default: casez_tmp = {2'h0, axi_awaddr[31:2] + 30'h1};
    endcase
  end  // always_comb
  reg  [31:0] casez_tmp_0;
  wire [31:0] _GEN_0 = {22'h0, axi_arlen, 2'h0};
  always_comb begin
    casez (axi_arburst)
      2'b00: casez_tmp_0 = axi_araddr;
      2'b01: casez_tmp_0 = {axi_araddr[31:2] + 30'h1, 2'h0};
      2'b10:
      casez_tmp_0 =
          {21'h0, axi_awaddr[10:0] & {1'h0, axi_arlen, 2'h0}} == _GEN_0
            ? axi_araddr - _GEN_0
            : {axi_araddr[31:2] + 30'h1, 2'h0};
      default: casez_tmp_0 = {2'h0, S_AXI_ARADDR[31:2] + 30'h1};
    endcase
  end  // always_comb
  wire _GEN_1 = ~axi_awready & S_AXI_AWVALID & ~axi_awv_awr_flag;
  wire _GEN_2 = _GEN_1 & ~axi_arv_arr_flag;
  wire _GEN_3 = S_AXI_WLAST & axi_wready;
  wire _GEN_4 = axi_awv_awr_flag & axi_wready & S_AXI_WVALID & ~axi_bvalid & S_AXI_WLAST;
  wire _GEN_5 = ~axi_arready & S_AXI_ARVALID;
  wire _GEN_6 = _GEN_5 & ~axi_awv_awr_flag & ~axi_arv_arr_flag;
  wire _GEN_7 = axi_rvalid & S_AXI_RREADY;
  wire _GEN_8 = axi_arlen_cntr == axi_arlen;
  wire _GEN_9 = _GEN_7 & _GEN_8;
  wire _GEN_10 = _GEN_5 & ~axi_arv_arr_flag;
  wire _GEN_11 = axi_arlen_cntr <= axi_arlen & axi_rvalid & S_AXI_RREADY;
  wire _GEN_12 = axi_arv_arr_flag & ~axi_rvalid;
  always @(posedge clock) begin
    if (reset) begin
      axi_awready <= 1'h0;
      axi_awv_awr_flag <= 1'h0;
      axi_awaddr <= 32'h0;
      axi_awburst <= 2'h0;
      axi_awlen <= 8'h0;
      axi_awlen_cntr <= 8'h0;
      axi_wready <= 1'h0;
      axi_bvalid <= 1'h0;
      axi_bresp <= 2'h0;
      axi_arready <= 1'h0;
      axi_araddr <= 32'h0;
      axi_arburst <= 2'h0;
      axi_arlen <= 8'h0;
      axi_arlen_cntr <= 8'h0;
      axi_arv_arr_flag <= 1'h0;
      axi_rvalid <= 1'h0;
      axi_rresp <= 2'h0;
      axi_rlast <= 1'h0;
    end else begin
      axi_awready <= _GEN_2 | _GEN_3 & axi_awready;
      axi_awv_awr_flag <= _GEN_2 | ~_GEN_3 & axi_awv_awr_flag;
      if (_GEN_1) begin
        axi_awaddr <= S_AXI_AWADDR;
        axi_awburst <= S_AXI_AWBURST;
        axi_awlen <= S_AXI_AWLEN;
        axi_awlen_cntr <= 8'h0;
      end else if (axi_awlen_cntr <= axi_awlen & axi_wready & S_AXI_WVALID) begin
        axi_awaddr <= casez_tmp;
        axi_awlen_cntr <= axi_awlen_cntr + 8'h1;
      end
      axi_wready <= ~axi_wready & S_AXI_WVALID & axi_awv_awr_flag | ~_GEN_3 & axi_wready;
      axi_bvalid <= _GEN_4 | ~(S_AXI_BREADY & axi_bvalid) & axi_bvalid;
      if (_GEN_4) axi_bresp <= {~_mmap_region_RAM_write_resp, 1'h0};
      axi_arready <= _GEN_6 | _GEN_9 & axi_arready;
      if (_GEN_10) begin
        axi_araddr <= S_AXI_ARADDR;
        axi_arburst <= S_AXI_ARBURST;
        axi_arlen <= S_AXI_ARLEN;
        axi_arlen_cntr <= 8'h0;
      end else if (_GEN_11) begin
        axi_araddr <= casez_tmp_0;
        axi_arlen_cntr <= axi_arlen_cntr + 8'h1;
      end
      axi_arv_arr_flag <= _GEN_6 | ~_GEN_9 & axi_arv_arr_flag;
      axi_rvalid <= _GEN_12 | ~_GEN_7 & axi_rvalid;
      if (_GEN_12) axi_rresp <= {~_mmap_region_RAM_read_resp, 1'h0};
      axi_rlast <=
        ~(_GEN_10 | _GEN_11)
        & (_GEN_8 & ~axi_rlast & axi_arv_arr_flag | ~S_AXI_RREADY & axi_rlast);
    end
  end  // always @(posedge)
  ram_32x32_s8_b65536 mmap_region (
      .clock         (clock),
      .reset         (reset),
      .RAM_write_en  (axi_wready & S_AXI_WVALID),
      .RAM_write_addr(axi_awaddr),
      .RAM_write_data(S_AXI_WDATA),
      .RAM_write_strb(S_AXI_WSTRB),
      .RAM_write_resp(_mmap_region_RAM_write_resp),
      .RAM_read_en   (axi_arv_arr_flag),
      .RAM_read_addr (axi_araddr),
      .RAM_read_data (_mmap_region_RAM_read_data),
      .RAM_read_resp (_mmap_region_RAM_read_resp)
  );
  assign S_AXI_AWREADY = axi_awready;
  assign S_AXI_WREADY = axi_wready;
  assign S_AXI_BRESP = axi_bresp;
  assign S_AXI_BVALID = axi_bvalid;
  assign S_AXI_BID = S_AXI_AWID;
  assign S_AXI_BUSER = 1'h0;
  assign S_AXI_ARREADY = axi_arready;
  assign S_AXI_RDATA = axi_rvalid & _mmap_region_RAM_read_resp ? _mmap_region_RAM_read_data : 32'h0;
  assign S_AXI_RRESP = axi_rresp;
  assign S_AXI_RVALID = axi_rvalid;
  assign S_AXI_RLAST = axi_rlast;
  assign S_AXI_RID = S_AXI_ARID;
  assign S_AXI_RUSER = 1'h0;
endmodule

