`timescale 1ns / 1ps
// Generated by CIRCT firtool-1.128.0
module uart_tx_b115200_f50000000 (
    input        clock,
    reset,
    output       UART_Tx_txd,
    UART_Tx_channel_ready,
    input        UART_Tx_channel_valid,
    input  [7:0] UART_Tx_channel_bits
);

  reg  [1:0] state;
  reg  [7:0] data;
  reg  [2:0] bitCounter;
  reg  [8:0] tickCounter;
  wire       tick = tickCounter == 9'h1B1;
  wire       UART_Tx_channel_ready_0 = state == 2'h0;
  wire       _GEN = state == 2'h1;
  wire       _GEN_0 = state == 2'h2;
  reg  [1:0] casez_tmp;
  always_comb begin
    casez (state)
      2'b00:   casez_tmp = UART_Tx_channel_valid ? 2'h1 : state;
      2'b01:   casez_tmp = tick ? 2'h2 : state;
      2'b10:   casez_tmp = tick & (&bitCounter) ? 2'h3 : state;
      default: casez_tmp = (&state) & tick ? 2'h0 : state;
    endcase
  end  // always_comb
  wire _GEN_1 = _GEN_0 & tick;
  always @(posedge clock) begin
    if (reset) begin
      state <= 2'h0;
      bitCounter <= 3'h0;
      tickCounter <= 9'h0;
    end else begin
      state <= casez_tmp;
      if (~UART_Tx_channel_ready_0) begin
        if (_GEN) begin
          if (tick) bitCounter <= 3'h0;
        end else
        if (~_GEN_1 | (&bitCounter)) begin
        end else bitCounter <= bitCounter + 3'h1;
      end
      tickCounter <=
        UART_Tx_channel_ready_0 & UART_Tx_channel_valid | tick
          ? 9'h0
          : tickCounter + 9'h1;
    end
    if (UART_Tx_channel_ready_0) begin
      if (UART_Tx_channel_valid) data <= UART_Tx_channel_bits;
    end else
    if (_GEN | ~_GEN_1 | (&bitCounter)) begin
    end else data <= {1'h0, data[7:1]};
  end  // always @(posedge)
  assign UART_Tx_txd = UART_Tx_channel_ready_0 | ~_GEN & (~_GEN_0 | data[0]);
  assign UART_Tx_channel_ready = UART_Tx_channel_ready_0;
endmodule

module uart_rx_b115200_f50000000 (
    input        clock,
    reset,
    UART_Rx_rxd,
    output       UART_Rx_channel_valid,
    output [7:0] UART_Rx_channel_bits,
    output       UART_Rx_error
);

  reg  [1:0] state;
  reg  [7:0] data;
  reg  [2:0] bitCounter;
  reg  [8:0] tickCounter;
  wire       tick = tickCounter == 9'h1B1;
  reg        rxd_REG;
  reg        rxd;
  wire       _GEN = state == 2'h0;
  wire       _GEN_0 = state == 2'h1;
  wire       _GEN_1 = state == 2'h2;
  wire       _GEN_2 = _GEN | _GEN_0 | _GEN_1;
  wire       _GEN_3 = (&state) & tick;
  reg  [1:0] casez_tmp;
  always_comb begin
    casez (state)
      2'b00:   casez_tmp = rxd ? state : 2'h1;
      2'b01:   casez_tmp = tick ? {~rxd, 1'h0} : state;
      2'b10:   casez_tmp = tick & (&bitCounter) ? 2'h3 : state;
      default: casez_tmp = _GEN_3 ? 2'h0 : state;
    endcase
  end  // always_comb
  wire _GEN_4 = _GEN_1 & tick;
  always @(posedge clock) begin
    if (reset) begin
      state <= 2'h0;
      bitCounter <= 3'h0;
      tickCounter <= 9'h0;
    end else begin
      state <= casez_tmp;
      if (~_GEN) begin
        if (_GEN_0) begin
          if (tick & ~rxd) bitCounter <= 3'h0;
        end else
        if (~_GEN_4 | (&bitCounter)) begin
        end else bitCounter <= bitCounter + 3'h1;
      end
      tickCounter <= _GEN & ~rxd ? 9'hD9 : tick ? 9'h0 : tickCounter + 9'h1;
    end
    if (_GEN | _GEN_0 | ~_GEN_4) begin
    end else data <= {rxd, data[7:1]};
    rxd_REG <= UART_Rx_rxd;
    rxd <= rxd_REG;
  end  // always @(posedge)
  assign UART_Rx_channel_valid = ~_GEN_2 & (&state) & tick;
  assign UART_Rx_channel_bits = _GEN_2 | ~_GEN_3 ? 8'h0 : data;
  assign UART_Rx_error = ~_GEN_2 & _GEN_3 & ~rxd;
endmodule

module uart_level_b115200_f50000000 (
    input         clock,
    reset,
    output        UART_CMD_txd,
    input         UART_CMD_rxd,
    output        UART_CMD_cmd_valid,
    output [ 1:0] UART_CMD_cmd_type,
    output [31:0] UART_CMD_cmd_addr,
    UART_CMD_cmd_wdata,
    input         UART_CMD_resp_valid,
    input  [31:0] UART_CMD_resp_rdata
);

  wire        _uart_rx_UART_Rx_channel_valid;
  wire [ 7:0] _uart_rx_UART_Rx_channel_bits;
  wire        _uart_rx_UART_Rx_error;
  wire        _uart_tx_UART_Tx_channel_ready;
  reg  [ 1:0] rx_state;
  reg  [ 3:0] rx_byte_cnt;
  reg  [ 7:0] rx_buffer_0;
  reg  [ 7:0] rx_buffer_1;
  reg  [ 7:0] rx_buffer_2;
  reg  [ 7:0] rx_buffer_3;
  reg  [ 7:0] rx_buffer_4;
  reg  [ 7:0] rx_buffer_5;
  reg  [ 7:0] rx_buffer_6;
  reg  [ 7:0] rx_buffer_7;
  reg         cmd_valid_reg;
  reg  [ 1:0] cmd_type_reg;
  reg  [31:0] cmd_addr_reg;
  reg  [31:0] cmd_wdata_reg;
  reg  [ 1:0] tx_state;
  reg  [ 2:0] tx_byte_cnt;
  reg  [ 7:0] tx_buffer_1;
  reg  [ 7:0] tx_buffer_2;
  reg  [ 7:0] tx_buffer_3;
  reg  [ 7:0] tx_buffer_4;
  reg  [ 3:0] tx_total_bytes;
  wire        _GEN = tx_state == 2'h0;
  wire        _GEN_0 = tx_state == 2'h1;
  reg  [ 7:0] casez_tmp;
  always_comb begin
    casez (tx_byte_cnt)
      3'b000:  casez_tmp = 8'h0;
      3'b001:  casez_tmp = tx_buffer_1;
      3'b010:  casez_tmp = tx_buffer_2;
      3'b011:  casez_tmp = tx_buffer_3;
      3'b100:  casez_tmp = tx_buffer_4;
      3'b101:  casez_tmp = 8'h0;
      3'b110:  casez_tmp = 8'h0;
      default: casez_tmp = 8'h0;
    endcase
  end  // always_comb
  wire       _GEN_1 = {1'h0, tx_byte_cnt} == tx_total_bytes - 4'h1;
  wire       _GEN_2 = rx_state == 2'h0;
  wire       _GEN_3 = _uart_rx_UART_Rx_channel_valid & ~_uart_rx_UART_Rx_error;
  wire       _GEN_4 = rx_state == 2'h1;
  wire [3:0] _next_byte_cnt_T = rx_byte_cnt + 4'h1;
  wire       _GEN_5 = _next_byte_cnt_T == 4'h9;
  wire       _GEN_6 = _GEN_4 & _GEN_3 & _GEN_5;
  wire       _GEN_7 = _GEN_2 | ~_GEN_6;
  wire       _GEN_8 = _GEN & UART_CMD_resp_valid;
  always @(posedge clock) begin
    if (reset) begin
      rx_state <= 2'h0;
      rx_byte_cnt <= 4'h0;
      cmd_valid_reg <= 1'h0;
      cmd_addr_reg <= 32'h0;
      cmd_wdata_reg <= 32'h0;
      tx_state <= 2'h0;
      tx_byte_cnt <= 3'h0;
      tx_total_bytes <= 4'h0;
    end else begin
      if (_GEN_2) begin
        if (_GEN_3) begin
          rx_state <= 2'h1;
          rx_byte_cnt <= 4'h1;
        end
      end else begin
        if (_GEN_6) rx_state <= 2'h0;
        if (_GEN_4 & _GEN_3) rx_byte_cnt <= _GEN_5 ? 4'h0 : _next_byte_cnt_T;
      end
      cmd_valid_reg <= ~_GEN_2 & _GEN_6;
      if (_GEN_7) begin
      end else begin
        cmd_addr_reg  <= {rx_buffer_4, rx_buffer_3, rx_buffer_2, rx_buffer_1};
        cmd_wdata_reg <= {_uart_rx_UART_Rx_channel_bits, rx_buffer_7, rx_buffer_6, rx_buffer_5};
      end
      if (_GEN) begin
        if (UART_CMD_resp_valid) begin
          tx_state <= 2'h1;
          tx_byte_cnt <= 3'h0;
        end
      end else begin
        if (_GEN_0 & _uart_tx_UART_Tx_channel_ready & _GEN_1) tx_state <= 2'h0;
        if (_GEN_0 & _uart_tx_UART_Tx_channel_ready)
          tx_byte_cnt <= _GEN_1 ? 3'h0 : tx_byte_cnt + 3'h1;
      end
      if (_GEN_8) tx_total_bytes <= 4'h5;
    end
    if ((_GEN_2 | _GEN_4 & rx_byte_cnt == 4'h0) & _GEN_3)
      rx_buffer_0 <= _uart_rx_UART_Rx_channel_bits;
    if (_GEN_2 | ~(_GEN_4 & _GEN_3 & rx_byte_cnt == 4'h1)) begin
    end else rx_buffer_1 <= _uart_rx_UART_Rx_channel_bits;
    if (_GEN_2 | ~(_GEN_4 & _GEN_3 & rx_byte_cnt == 4'h2)) begin
    end else rx_buffer_2 <= _uart_rx_UART_Rx_channel_bits;
    if (_GEN_2 | ~(_GEN_4 & _GEN_3 & rx_byte_cnt == 4'h3)) begin
    end else rx_buffer_3 <= _uart_rx_UART_Rx_channel_bits;
    if (_GEN_2 | ~(_GEN_4 & _GEN_3 & rx_byte_cnt == 4'h4)) begin
    end else rx_buffer_4 <= _uart_rx_UART_Rx_channel_bits;
    if (_GEN_2 | ~(_GEN_4 & _GEN_3 & rx_byte_cnt == 4'h5)) begin
    end else rx_buffer_5 <= _uart_rx_UART_Rx_channel_bits;
    if (_GEN_2 | ~(_GEN_4 & _GEN_3 & rx_byte_cnt == 4'h6)) begin
    end else rx_buffer_6 <= _uart_rx_UART_Rx_channel_bits;
    if (_GEN_2 | ~(_GEN_4 & _GEN_3 & rx_byte_cnt == 4'h7)) begin
    end else rx_buffer_7 <= _uart_rx_UART_Rx_channel_bits;
    if (_GEN_7) begin
    end else cmd_type_reg <= rx_buffer_0 == 8'h2 ? 2'h2 : {1'h0, rx_buffer_0 == 8'h1};
    if (_GEN_8) begin
      tx_buffer_1 <= UART_CMD_resp_rdata[7:0];
      tx_buffer_2 <= UART_CMD_resp_rdata[15:8];
      tx_buffer_3 <= UART_CMD_resp_rdata[23:16];
      tx_buffer_4 <= UART_CMD_resp_rdata[31:24];
    end
  end  // always @(posedge)
  uart_tx_b115200_f50000000 uart_tx (
      .clock                (clock),
      .reset                (reset),
      .UART_Tx_txd          (UART_CMD_txd),
      .UART_Tx_channel_ready(_uart_tx_UART_Tx_channel_ready),
      .UART_Tx_channel_valid(~_GEN & _GEN_0),
      .UART_Tx_channel_bits (_GEN | ~_GEN_0 ? 8'h0 : casez_tmp)
  );
  uart_rx_b115200_f50000000 uart_rx (
      .clock                (clock),
      .reset                (reset),
      .UART_Rx_rxd          (UART_CMD_rxd),
      .UART_Rx_channel_valid(_uart_rx_UART_Rx_channel_valid),
      .UART_Rx_channel_bits (_uart_rx_UART_Rx_channel_bits),
      .UART_Rx_error        (_uart_rx_UART_Rx_error)
  );
  assign UART_CMD_cmd_valid = cmd_valid_reg;
  assign UART_CMD_cmd_type  = cmd_type_reg;
  assign UART_CMD_cmd_addr  = cmd_addr_reg;
  assign UART_CMD_cmd_wdata = cmd_wdata_reg;
endmodule

module axilite_master_uart_cmd_32x32_b115200_f50000000 (
    input         clock,
    reset,
    output [31:0] M_AXI_AWADDR,
    output        M_AXI_AWVALID,
    input         M_AXI_AWREADY,
    output [31:0] M_AXI_WDATA,
    output        M_AXI_WVALID,
    input         M_AXI_WREADY,
    M_AXI_BVALID,
    output        M_AXI_BREADY,
    output [31:0] M_AXI_ARADDR,
    output        M_AXI_ARVALID,
    input         M_AXI_ARREADY,
    input  [31:0] M_AXI_RDATA,
    input         M_AXI_RVALID,
    output        M_AXI_RREADY,
    TX,
    input         RX
);

  wire        _uart_cmd_UART_CMD_cmd_valid;
  wire [ 1:0] _uart_cmd_UART_CMD_cmd_type;
  wire [31:0] _uart_cmd_UART_CMD_cmd_addr;
  wire [31:0] _uart_cmd_UART_CMD_cmd_wdata;
  reg  [ 3:0] state;
  reg  [31:0] axi_awaddr;
  reg         axi_awvalid;
  reg  [31:0] axi_wdata;
  reg         axi_wvalid;
  reg         axi_bready;
  reg  [31:0] axi_araddr;
  reg         axi_arvalid;
  reg         axi_rready;
  reg         aw_done;
  reg         w_done;
  reg  [31:0] move_dst_addr;
  reg  [31:0] move_data_buf;
  wire        _GEN = state == 4'h0;
  reg  [31:0] casez_tmp;
  always_comb begin
    casez (_uart_cmd_UART_CMD_cmd_type)
      2'b00:   casez_tmp = axi_araddr;
      2'b01:   casez_tmp = _uart_cmd_UART_CMD_cmd_addr;
      2'b10:   casez_tmp = _uart_cmd_UART_CMD_cmd_addr;
      default: casez_tmp = axi_araddr;
    endcase
  end  // always_comb
  reg [3:0] casez_tmp_0;
  always_comb begin
    casez (_uart_cmd_UART_CMD_cmd_type)
      2'b00:   casez_tmp_0 = 4'h1;
      2'b01:   casez_tmp_0 = 4'h4;
      2'b10:   casez_tmp_0 = 4'h6;
      default: casez_tmp_0 = state;
    endcase
  end  // always_comb
  wire _GEN_0 = state == 4'h1;
  wire _GEN_1 = state == 4'h3;
  wire _GEN_2 = M_AXI_BVALID & axi_bready;
  wire _GEN_3 = state == 4'h4;
  wire _GEN_4 = state == 4'h5;
  wire _GEN_5 = M_AXI_RVALID & axi_rready;
  wire _GEN_6 = state == 4'h6;
  wire _GEN_7 = state == 4'h7;
  wire _GEN_8 = state == 4'h8;
  wire _GEN_9 = state == 4'h9;
  wire _GEN_10 = _GEN_9 & _GEN_2;
  wire _GEN_11 = _GEN_6 | _GEN_7 | _GEN_8;
  wire _GEN_12 = M_AXI_AWREADY & axi_awvalid;
  wire _GEN_13 = M_AXI_WREADY & axi_wvalid;
  wire _GEN_14 = aw_done & w_done;
  wire _GEN_15 = _GEN_14 | axi_bready;
  wire _GEN_16 = _GEN_8 & _GEN_12;
  wire _GEN_17 = _GEN_8 & _GEN_13;
  wire _GEN_18 = _uart_cmd_UART_CMD_cmd_type == 2'h0;
  wire _GEN_19 = _uart_cmd_UART_CMD_cmd_type == 2'h1;
  wire _GEN_20 = _uart_cmd_UART_CMD_cmd_type == 2'h2;
  wire _GEN_21 = _GEN & _uart_cmd_UART_CMD_cmd_valid;
  wire _GEN_22 = M_AXI_ARREADY & axi_arvalid;
  wire _GEN_23 = _GEN_0 | _GEN_1;
  wire _GEN_24 = _GEN_7 & _GEN_5;
  wire _GEN_25 = _GEN_1 | _GEN_3 | _GEN_4 | _GEN_6;
  wire _GEN_26 = _GEN_0 | _GEN_25;
  wire _GEN_27 = _uart_cmd_UART_CMD_cmd_valid & _GEN_18;
  wire _GEN_28 = _GEN_22 | axi_rready;
  always @(posedge clock) begin
    if (reset) begin
      state <= 4'h0;
      axi_awaddr <= 32'h0;
      axi_awvalid <= 1'h0;
      axi_wdata <= 32'h0;
      axi_wvalid <= 1'h0;
      axi_bready <= 1'h0;
      axi_araddr <= 32'h0;
      axi_arvalid <= 1'h0;
      axi_rready <= 1'h0;
      aw_done <= 1'h0;
      w_done <= 1'h0;
      move_dst_addr <= 32'h0;
      move_data_buf <= 32'h0;
    end else begin
      if (_GEN) begin
        if (_uart_cmd_UART_CMD_cmd_valid) state <= casez_tmp_0;
        if (_GEN_27) begin
          axi_awaddr <= _uart_cmd_UART_CMD_cmd_addr;
          axi_wdata  <= _uart_cmd_UART_CMD_cmd_wdata;
        end
        axi_awvalid <= _GEN_27 | axi_awvalid;
        axi_wvalid <= _GEN_27 | axi_wvalid;
        axi_arvalid <= _uart_cmd_UART_CMD_cmd_valid & ~_GEN_18 & (_GEN_19 | _GEN_20) | axi_arvalid;
        aw_done <= ~_GEN_27 & aw_done;
        w_done <= ~_GEN_27 & w_done;
      end else begin
        if (_GEN_0) begin
          if (_GEN_14) state <= 4'h3;
          axi_awvalid <= ~_GEN_12 & axi_awvalid;
          axi_wvalid <= ~_GEN_13 & axi_wvalid;
          axi_bready <= _GEN_15;
          aw_done <= _GEN_12 | aw_done;
          w_done <= _GEN_13 | w_done;
        end else begin
          if (_GEN_1) begin
            if (_GEN_2) state <= 4'h0;
            axi_bready <= ~_GEN_2 & axi_bready;
          end else begin
            if (_GEN_3) begin
              if (_GEN_22) state <= 4'h5;
            end else if (_GEN_4) begin
              if (_GEN_5) state <= 4'h0;
            end else if (_GEN_6) begin
              if (_GEN_22) state <= 4'h7;
            end else if (_GEN_7) begin
              if (_GEN_5) state <= 4'h8;
            end else if (_GEN_8) begin
              if (_GEN_14) state <= 4'h9;
            end else if (_GEN_10) state <= 4'h0;
            if (~(_GEN_3 | _GEN_4 | _GEN_6 | _GEN_7))
              axi_bready <= _GEN_8 ? _GEN_15 : ~_GEN_10 & axi_bready;
          end
          if (~_GEN_25) begin
            axi_awvalid <= _GEN_7 ? _GEN_5 | axi_awvalid : ~_GEN_16 & axi_awvalid;
            axi_wvalid <= _GEN_7 ? _GEN_5 | axi_wvalid : ~_GEN_17 & axi_wvalid;
            aw_done <= _GEN_7 ? ~_GEN_5 & aw_done : _GEN_16 | aw_done;
            w_done <= _GEN_7 ? ~_GEN_5 & w_done : _GEN_17 | w_done;
          end
        end
        if (_GEN_26 | ~_GEN_24) begin
        end else begin
          axi_awaddr <= move_dst_addr;
          axi_wdata  <= M_AXI_RDATA;
        end
        if (~_GEN_23)
          axi_arvalid <=
            _GEN_3
              ? ~_GEN_22 & axi_arvalid
              : (_GEN_4 | ~(_GEN_6 & _GEN_22)) & axi_arvalid;
      end
      if (_GEN_21) axi_araddr <= casez_tmp;
      if (~(_GEN | _GEN_23))
        axi_rready <=
          _GEN_3
            ? _GEN_28
            : _GEN_4 ? ~_GEN_5 & axi_rready : _GEN_6 ? _GEN_28 : ~_GEN_24 & axi_rready;
      if (~_GEN_21 | _GEN_18 | _GEN_19 | ~_GEN_20) begin
      end else move_dst_addr <= _uart_cmd_UART_CMD_cmd_wdata;
      if (_GEN | _GEN_26 | ~_GEN_24) begin
      end else move_data_buf <= M_AXI_RDATA;
    end
  end  // always @(posedge)
  uart_level_b115200_f50000000 uart_cmd (
      .clock(clock),
      .reset(reset),
      .UART_CMD_txd(TX),
      .UART_CMD_rxd(RX),
      .UART_CMD_cmd_valid(_uart_cmd_UART_CMD_cmd_valid),
      .UART_CMD_cmd_type(_uart_cmd_UART_CMD_cmd_type),
      .UART_CMD_cmd_addr(_uart_cmd_UART_CMD_cmd_addr),
      .UART_CMD_cmd_wdata(_uart_cmd_UART_CMD_cmd_wdata),
      .UART_CMD_resp_valid
      (~(_GEN | _GEN_0)
       & (_GEN_1 ? _GEN_2 : ~_GEN_3 & (_GEN_4 ? _GEN_5 : ~_GEN_11 & _GEN_9 & _GEN_2))),
      .UART_CMD_resp_rdata
      (_GEN | _GEN_0 | _GEN_1 | _GEN_3
         ? 32'h0
         : _GEN_4
             ? (_GEN_5 ? M_AXI_RDATA : 32'h0)
             : _GEN_11 | ~_GEN_10 ? 32'h0 : move_data_buf)
  );
  assign M_AXI_AWADDR  = axi_awaddr;
  assign M_AXI_AWVALID = axi_awvalid;
  assign M_AXI_WDATA   = axi_wdata;
  assign M_AXI_WVALID  = axi_wvalid;
  assign M_AXI_BREADY  = axi_bready;
  assign M_AXI_ARADDR  = axi_araddr;
  assign M_AXI_ARVALID = axi_arvalid;
  assign M_AXI_RREADY  = axi_rready;
endmodule

module axi_lite2full_32x32_i4_u1 (
    input  [31:0] S_AXI_AWADDR,
    input         S_AXI_AWVALID,
    output        S_AXI_AWREADY,
    input  [31:0] S_AXI_WDATA,
    input         S_AXI_WVALID,
    output        S_AXI_WREADY,
    S_AXI_BVALID,
    input         S_AXI_BREADY,
    input  [31:0] S_AXI_ARADDR,
    input         S_AXI_ARVALID,
    output        S_AXI_ARREADY,
    output [31:0] S_AXI_RDATA,
    output        S_AXI_RVALID,
    input         S_AXI_RREADY,
    output [31:0] M_AXI_AWADDR,
    output        M_AXI_AWVALID,
    input         M_AXI_AWREADY,
    output [31:0] M_AXI_WDATA,
    output        M_AXI_WVALID,
    input         M_AXI_WREADY,
    output        M_AXI_BREADY,
    input         M_AXI_BVALID,
    output [31:0] M_AXI_ARADDR,
    output        M_AXI_ARVALID,
    input         M_AXI_ARREADY,
    output        M_AXI_RREADY,
    input  [31:0] M_AXI_RDATA,
    input         M_AXI_RVALID
);

  assign S_AXI_AWREADY = M_AXI_AWREADY;
  assign S_AXI_WREADY  = M_AXI_WREADY;
  assign S_AXI_BVALID  = M_AXI_BVALID;
  assign S_AXI_ARREADY = M_AXI_ARREADY;
  assign S_AXI_RDATA   = M_AXI_RDATA;
  assign S_AXI_RVALID  = M_AXI_RVALID;
  assign M_AXI_AWADDR  = S_AXI_AWADDR;
  assign M_AXI_AWVALID = S_AXI_AWVALID;
  assign M_AXI_WDATA   = S_AXI_WDATA;
  assign M_AXI_WVALID  = S_AXI_WVALID;
  assign M_AXI_BREADY  = S_AXI_BREADY;
  assign M_AXI_ARADDR  = S_AXI_ARADDR;
  assign M_AXI_ARVALID = S_AXI_ARVALID;
  assign M_AXI_RREADY  = S_AXI_RREADY;
endmodule

module axilite_interconnect4_32x32 (
    input  [31:0] S_AXI_AWADDR,
    input         S_AXI_AWVALID,
    output        S_AXI_AWREADY,
    input  [31:0] S_AXI_WDATA,
    input         S_AXI_WVALID,
    output        S_AXI_WREADY,
    S_AXI_BVALID,
    input         S_AXI_BREADY,
    input  [31:0] S_AXI_ARADDR,
    input         S_AXI_ARVALID,
    output        S_AXI_ARREADY,
    output [31:0] S_AXI_RDATA,
    output        S_AXI_RVALID,
    input         S_AXI_RREADY,
    output [31:0] M_AXI_0_AWADDR,
    output        M_AXI_0_AWVALID,
    input         M_AXI_0_AWREADY,
    output [31:0] M_AXI_0_WDATA,
    output        M_AXI_0_WVALID,
    input         M_AXI_0_WREADY,
    M_AXI_0_BVALID,
    output        M_AXI_0_BREADY,
    output [31:0] M_AXI_0_ARADDR,
    output        M_AXI_0_ARVALID,
    input         M_AXI_0_ARREADY,
    input  [31:0] M_AXI_0_RDATA,
    input         M_AXI_0_RVALID,
    output        M_AXI_0_RREADY,
    output [31:0] M_AXI_1_AWADDR,
    output        M_AXI_1_AWVALID,
    input         M_AXI_1_AWREADY,
    output [31:0] M_AXI_1_WDATA,
    output        M_AXI_1_WVALID,
    input         M_AXI_1_WREADY,
    M_AXI_1_BVALID,
    output        M_AXI_1_BREADY,
    output [31:0] M_AXI_1_ARADDR,
    output        M_AXI_1_ARVALID,
    input         M_AXI_1_ARREADY,
    input  [31:0] M_AXI_1_RDATA,
    input         M_AXI_1_RVALID,
    output        M_AXI_1_RREADY,
    output [31:0] M_AXI_2_AWADDR,
    output        M_AXI_2_AWVALID,
    input         M_AXI_2_AWREADY,
    output [31:0] M_AXI_2_WDATA,
    output        M_AXI_2_WVALID,
    input         M_AXI_2_WREADY,
    M_AXI_2_BVALID,
    output        M_AXI_2_BREADY,
    output [31:0] M_AXI_2_ARADDR,
    output        M_AXI_2_ARVALID,
    input         M_AXI_2_ARREADY,
    input  [31:0] M_AXI_2_RDATA,
    input         M_AXI_2_RVALID,
    output        M_AXI_2_RREADY,
    output [31:0] M_AXI_3_AWADDR,
    output        M_AXI_3_AWVALID,
    input         M_AXI_3_AWREADY,
    output [31:0] M_AXI_3_WDATA,
    output        M_AXI_3_WVALID,
    input         M_AXI_3_WREADY,
    M_AXI_3_BVALID,
    output        M_AXI_3_BREADY,
    output [31:0] M_AXI_3_ARADDR,
    output        M_AXI_3_ARVALID,
    input         M_AXI_3_ARREADY,
    input  [31:0] M_AXI_3_RDATA,
    input         M_AXI_3_RVALID,
    output        M_AXI_3_RREADY
);

  wire _slave_b_bits_T_43 = S_AXI_AWADDR < 32'h30000;
  wire _slave_b_bits_T_45 = S_AXI_AWADDR > 32'h2FFFF;
  wire _slave_b_bits_T_46 = S_AXI_AWADDR < 32'h40000;
  wire _slave_b_bits_T_49 = S_AXI_AWADDR < 32'h50000;
  wire _slave_r_bits_T_43 = S_AXI_ARADDR < 32'h30000;
  wire _slave_r_bits_T_45 = S_AXI_ARADDR > 32'h2FFFF;
  wire _slave_r_bits_T_46 = S_AXI_ARADDR < 32'h40000;
  wire _slave_r_bits_T_49 = S_AXI_ARADDR < 32'h50000;
  assign S_AXI_AWREADY =
    ((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
       ? 2'h3
       : _slave_b_bits_T_45 & _slave_b_bits_T_46
           ? 2'h2
           : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}) == 2'h0
    & M_AXI_0_AWREADY
    | ((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
         ? 2'h3
         : _slave_b_bits_T_45 & _slave_b_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}) == 2'h1
    & M_AXI_1_AWREADY
    | ((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
         ? 2'h3
         : _slave_b_bits_T_45 & _slave_b_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}) == 2'h2
    & M_AXI_2_AWREADY
    | (&((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
           ? 2'h3
           : _slave_b_bits_T_45 & _slave_b_bits_T_46
               ? 2'h2
               : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}))
    & M_AXI_3_AWREADY;
  assign S_AXI_WREADY =
    ((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
       ? 2'h3
       : _slave_b_bits_T_45 & _slave_b_bits_T_46
           ? 2'h2
           : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}) == 2'h0
    & M_AXI_0_WREADY
    | ((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
         ? 2'h3
         : _slave_b_bits_T_45 & _slave_b_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}) == 2'h1
    & M_AXI_1_WREADY
    | ((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
         ? 2'h3
         : _slave_b_bits_T_45 & _slave_b_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}) == 2'h2
    & M_AXI_2_WREADY
    | (&((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
           ? 2'h3
           : _slave_b_bits_T_45 & _slave_b_bits_T_46
               ? 2'h2
               : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43})) & M_AXI_3_WREADY;
  assign S_AXI_BVALID =
    ((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
       ? 2'h3
       : _slave_b_bits_T_45 & _slave_b_bits_T_46
           ? 2'h2
           : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}) == 2'h0
    & M_AXI_0_BVALID
    | ((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
         ? 2'h3
         : _slave_b_bits_T_45 & _slave_b_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}) == 2'h1
    & M_AXI_1_BVALID
    | ((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
         ? 2'h3
         : _slave_b_bits_T_45 & _slave_b_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}) == 2'h2
    & M_AXI_2_BVALID
    | (&((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
           ? 2'h3
           : _slave_b_bits_T_45 & _slave_b_bits_T_46
               ? 2'h2
               : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43})) & M_AXI_3_BVALID;
  assign S_AXI_ARREADY =
    ((|(S_AXI_ARADDR[31:18])) & _slave_r_bits_T_49
       ? 2'h3
       : _slave_r_bits_T_45 & _slave_r_bits_T_46
           ? 2'h2
           : {1'h0, (|(S_AXI_ARADDR[31:17])) & _slave_r_bits_T_43}) == 2'h0
    & M_AXI_0_ARREADY
    | ((|(S_AXI_ARADDR[31:18])) & _slave_r_bits_T_49
         ? 2'h3
         : _slave_r_bits_T_45 & _slave_r_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_ARADDR[31:17])) & _slave_r_bits_T_43}) == 2'h1
    & M_AXI_1_ARREADY
    | ((|(S_AXI_ARADDR[31:18])) & _slave_r_bits_T_49
         ? 2'h3
         : _slave_r_bits_T_45 & _slave_r_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_ARADDR[31:17])) & _slave_r_bits_T_43}) == 2'h2
    & M_AXI_2_ARREADY
    | (&((|(S_AXI_ARADDR[31:18])) & _slave_r_bits_T_49
           ? 2'h3
           : _slave_r_bits_T_45 & _slave_r_bits_T_46
               ? 2'h2
               : {1'h0, (|(S_AXI_ARADDR[31:17])) & _slave_r_bits_T_43}))
    & M_AXI_3_ARREADY;
  assign S_AXI_RDATA =
    (((|(S_AXI_ARADDR[31:18])) & _slave_r_bits_T_49
        ? 2'h3
        : _slave_r_bits_T_45 & _slave_r_bits_T_46
            ? 2'h2
            : {1'h0, (|(S_AXI_ARADDR[31:17])) & _slave_r_bits_T_43}) == 2'h0
       ? M_AXI_0_RDATA
       : 32'h0)
    | (((|(S_AXI_ARADDR[31:18])) & _slave_r_bits_T_49
          ? 2'h3
          : _slave_r_bits_T_45 & _slave_r_bits_T_46
              ? 2'h2
              : {1'h0, (|(S_AXI_ARADDR[31:17])) & _slave_r_bits_T_43}) == 2'h1
         ? M_AXI_1_RDATA
         : 32'h0)
    | (((|(S_AXI_ARADDR[31:18])) & _slave_r_bits_T_49
          ? 2'h3
          : _slave_r_bits_T_45 & _slave_r_bits_T_46
              ? 2'h2
              : {1'h0, (|(S_AXI_ARADDR[31:17])) & _slave_r_bits_T_43}) == 2'h2
         ? M_AXI_2_RDATA
         : 32'h0)
    | ((&((|(S_AXI_ARADDR[31:18])) & _slave_r_bits_T_49
            ? 2'h3
            : _slave_r_bits_T_45 & _slave_r_bits_T_46
                ? 2'h2
                : {1'h0, (|(S_AXI_ARADDR[31:17])) & _slave_r_bits_T_43}))
         ? M_AXI_3_RDATA
         : 32'h0);
  assign S_AXI_RVALID =
    ((|(S_AXI_ARADDR[31:18])) & _slave_r_bits_T_49
       ? 2'h3
       : _slave_r_bits_T_45 & _slave_r_bits_T_46
           ? 2'h2
           : {1'h0, (|(S_AXI_ARADDR[31:17])) & _slave_r_bits_T_43}) == 2'h0
    & M_AXI_0_RVALID
    | ((|(S_AXI_ARADDR[31:18])) & _slave_r_bits_T_49
         ? 2'h3
         : _slave_r_bits_T_45 & _slave_r_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_ARADDR[31:17])) & _slave_r_bits_T_43}) == 2'h1
    & M_AXI_1_RVALID
    | ((|(S_AXI_ARADDR[31:18])) & _slave_r_bits_T_49
         ? 2'h3
         : _slave_r_bits_T_45 & _slave_r_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_ARADDR[31:17])) & _slave_r_bits_T_43}) == 2'h2
    & M_AXI_2_RVALID
    | (&((|(S_AXI_ARADDR[31:18])) & _slave_r_bits_T_49
           ? 2'h3
           : _slave_r_bits_T_45 & _slave_r_bits_T_46
               ? 2'h2
               : {1'h0, (|(S_AXI_ARADDR[31:17])) & _slave_r_bits_T_43})) & M_AXI_3_RVALID;
  assign M_AXI_0_AWADDR = S_AXI_AWADDR;
  assign M_AXI_0_AWVALID =
    S_AXI_AWVALID
    & ((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
         ? 2'h3
         : _slave_b_bits_T_45 & _slave_b_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}) == 2'h0;
  assign M_AXI_0_WDATA = S_AXI_WDATA;
  assign M_AXI_0_WVALID =
    S_AXI_WVALID
    & ((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
         ? 2'h3
         : _slave_b_bits_T_45 & _slave_b_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}) == 2'h0;
  assign M_AXI_0_BREADY =
    S_AXI_BREADY
    & ((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
         ? 2'h3
         : _slave_b_bits_T_45 & _slave_b_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}) == 2'h0;
  assign M_AXI_0_ARADDR = S_AXI_ARADDR;
  assign M_AXI_0_ARVALID =
    S_AXI_ARVALID
    & ((|(S_AXI_ARADDR[31:18])) & _slave_r_bits_T_49
         ? 2'h3
         : _slave_r_bits_T_45 & _slave_r_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_ARADDR[31:17])) & _slave_r_bits_T_43}) == 2'h0;
  assign M_AXI_0_RREADY =
    S_AXI_RREADY
    & ((|(S_AXI_ARADDR[31:18])) & _slave_r_bits_T_49
         ? 2'h3
         : _slave_r_bits_T_45 & _slave_r_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_ARADDR[31:17])) & _slave_r_bits_T_43}) == 2'h0;
  assign M_AXI_1_AWADDR = S_AXI_AWADDR;
  assign M_AXI_1_AWVALID =
    S_AXI_AWVALID
    & ((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
         ? 2'h3
         : _slave_b_bits_T_45 & _slave_b_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}) == 2'h1;
  assign M_AXI_1_WDATA = S_AXI_WDATA;
  assign M_AXI_1_WVALID =
    S_AXI_WVALID
    & ((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
         ? 2'h3
         : _slave_b_bits_T_45 & _slave_b_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}) == 2'h1;
  assign M_AXI_1_BREADY =
    S_AXI_BREADY
    & ((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
         ? 2'h3
         : _slave_b_bits_T_45 & _slave_b_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}) == 2'h1;
  assign M_AXI_1_ARADDR = S_AXI_ARADDR;
  assign M_AXI_1_ARVALID =
    S_AXI_ARVALID
    & ((|(S_AXI_ARADDR[31:18])) & _slave_r_bits_T_49
         ? 2'h3
         : _slave_r_bits_T_45 & _slave_r_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_ARADDR[31:17])) & _slave_r_bits_T_43}) == 2'h1;
  assign M_AXI_1_RREADY =
    S_AXI_RREADY
    & ((|(S_AXI_ARADDR[31:18])) & _slave_r_bits_T_49
         ? 2'h3
         : _slave_r_bits_T_45 & _slave_r_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_ARADDR[31:17])) & _slave_r_bits_T_43}) == 2'h1;
  assign M_AXI_2_AWADDR = S_AXI_AWADDR;
  assign M_AXI_2_AWVALID =
    S_AXI_AWVALID
    & ((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
         ? 2'h3
         : _slave_b_bits_T_45 & _slave_b_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}) == 2'h2;
  assign M_AXI_2_WDATA = S_AXI_WDATA;
  assign M_AXI_2_WVALID =
    S_AXI_WVALID
    & ((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
         ? 2'h3
         : _slave_b_bits_T_45 & _slave_b_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}) == 2'h2;
  assign M_AXI_2_BREADY =
    S_AXI_BREADY
    & ((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
         ? 2'h3
         : _slave_b_bits_T_45 & _slave_b_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}) == 2'h2;
  assign M_AXI_2_ARADDR = S_AXI_ARADDR;
  assign M_AXI_2_ARVALID =
    S_AXI_ARVALID
    & ((|(S_AXI_ARADDR[31:18])) & _slave_r_bits_T_49
         ? 2'h3
         : _slave_r_bits_T_45 & _slave_r_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_ARADDR[31:17])) & _slave_r_bits_T_43}) == 2'h2;
  assign M_AXI_2_RREADY =
    S_AXI_RREADY
    & ((|(S_AXI_ARADDR[31:18])) & _slave_r_bits_T_49
         ? 2'h3
         : _slave_r_bits_T_45 & _slave_r_bits_T_46
             ? 2'h2
             : {1'h0, (|(S_AXI_ARADDR[31:17])) & _slave_r_bits_T_43}) == 2'h2;
  assign M_AXI_3_AWADDR = S_AXI_AWADDR;
  assign M_AXI_3_AWVALID =
    S_AXI_AWVALID
    & (&((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
           ? 2'h3
           : _slave_b_bits_T_45 & _slave_b_bits_T_46
               ? 2'h2
               : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}));
  assign M_AXI_3_WDATA = S_AXI_WDATA;
  assign M_AXI_3_WVALID =
    S_AXI_WVALID
    & (&((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
           ? 2'h3
           : _slave_b_bits_T_45 & _slave_b_bits_T_46
               ? 2'h2
               : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}));
  assign M_AXI_3_BREADY =
    S_AXI_BREADY
    & (&((|(S_AXI_AWADDR[31:18])) & _slave_b_bits_T_49
           ? 2'h3
           : _slave_b_bits_T_45 & _slave_b_bits_T_46
               ? 2'h2
               : {1'h0, (|(S_AXI_AWADDR[31:17])) & _slave_b_bits_T_43}));
  assign M_AXI_3_ARADDR = S_AXI_ARADDR;
  assign M_AXI_3_ARVALID =
    S_AXI_ARVALID
    & (&((|(S_AXI_ARADDR[31:18])) & _slave_r_bits_T_49
           ? 2'h3
           : _slave_r_bits_T_45 & _slave_r_bits_T_46
               ? 2'h2
               : {1'h0, (|(S_AXI_ARADDR[31:17])) & _slave_r_bits_T_43}));
  assign M_AXI_3_RREADY =
    S_AXI_RREADY
    & (&((|(S_AXI_ARADDR[31:18])) & _slave_r_bits_T_49
           ? 2'h3
           : _slave_r_bits_T_45 & _slave_r_bits_T_46
               ? 2'h2
               : {1'h0, (|(S_AXI_ARADDR[31:17])) & _slave_r_bits_T_43}));
endmodule

module mmap_regs_32x32_r4 (
    input         clock,
    reset,
    MMAP_write_en,
    input  [31:0] MMAP_write_addr,
    MMAP_write_data,
    input         MMAP_read_en,
    input  [31:0] MMAP_read_addr,
    output [31:0] MMAP_read_data
);

  reg [31:0] regs_0;
  reg [31:0] regs_1;
  reg [31:0] regs_2;
  reg [31:0] regs_3;
  wire _MMAP_read_data_T = MMAP_read_addr == 32'h10000;
  wire _MMAP_read_data_T_1 = MMAP_read_addr == 32'h14000;
  wire _MMAP_read_data_T_2 = MMAP_read_addr == 32'h18000;
  wire _MMAP_read_data_T_3 = MMAP_read_addr == 32'h1C000;
  wire _write_addr_match_T = MMAP_write_addr == 32'h10000;
  wire _write_addr_match_T_1 = MMAP_write_addr == 32'h14000;
  wire _write_addr_match_T_2 = MMAP_write_addr == 32'h18000;
  wire _write_addr_match_T_3 = MMAP_write_addr == 32'h1C000;
  wire        _GEN =
    MMAP_write_en
    & (_write_addr_match_T | _write_addr_match_T_1 | _write_addr_match_T_2
       | _write_addr_match_T_3);
  always @(posedge clock) begin
    if (reset) begin
      regs_0 <= 32'h0;
      regs_1 <= 32'h0;
      regs_2 <= 32'h0;
      regs_3 <= 32'h0;
    end else begin
      if (_GEN & _write_addr_match_T) regs_0 <= MMAP_write_data;
      if (_GEN & _write_addr_match_T_1) regs_1 <= MMAP_write_data;
      if (_GEN & _write_addr_match_T_2) regs_2 <= MMAP_write_data;
      if (_GEN & _write_addr_match_T_3) regs_3 <= MMAP_write_data;
    end
  end  // always @(posedge)
  assign MMAP_read_data =
    MMAP_read_en
    & (_MMAP_read_data_T | _MMAP_read_data_T_1 | _MMAP_read_data_T_2
       | _MMAP_read_data_T_3)
      ? (_MMAP_read_data_T
           ? regs_0
           : _MMAP_read_data_T_1
               ? regs_1
               : _MMAP_read_data_T_2 ? regs_2 : _MMAP_read_data_T_3 ? regs_3 : 32'h0)
      : 32'h0;
endmodule

module axilite_slave_mmap_32x32_r4 (
    input         clock,
    reset,
    input  [31:0] S_AXI_AWADDR,
    input         S_AXI_AWVALID,
    output        S_AXI_AWREADY,
    input  [31:0] S_AXI_WDATA,
    input         S_AXI_WVALID,
    output        S_AXI_WREADY,
    S_AXI_BVALID,
    input         S_AXI_BREADY,
    input  [31:0] S_AXI_ARADDR,
    input         S_AXI_ARVALID,
    output        S_AXI_ARREADY,
    output [31:0] S_AXI_RDATA,
    output        S_AXI_RVALID,
    input         S_AXI_RREADY
);

  wire [31:0] _mmap_regs_MMAP_read_data;
  reg         axi_awready;
  reg  [31:0] axi_awaddr;
  reg         axi_wready;
  reg         axi_bvalid;
  reg         axi_arready;
  reg  [31:0] axi_araddr;
  reg  [31:0] axi_rdata;
  reg         axi_rvalid;
  wire        _GEN = ~axi_awready & S_AXI_AWVALID;
  wire        _GEN_0 = ~axi_arready & S_AXI_ARVALID;
  always @(posedge clock) begin
    if (reset) begin
      axi_awready <= 1'h0;
      axi_awaddr  <= 32'h0;
      axi_wready  <= 1'h0;
      axi_bvalid  <= 1'h0;
      axi_arready <= 1'h0;
      axi_araddr  <= 32'h0;
      axi_rdata   <= 32'h0;
      axi_rvalid  <= 1'h0;
    end else begin
      axi_awready <= _GEN;
      if (_GEN) axi_awaddr <= S_AXI_AWADDR;
      axi_wready <=
        ~axi_wready & axi_awready & S_AXI_AWVALID | ~(axi_wready & S_AXI_WVALID)
        & axi_wready;
      axi_bvalid <=
        ~axi_bvalid & axi_wready & S_AXI_WVALID | ~(S_AXI_BREADY & axi_bvalid)
        & axi_bvalid;
      axi_arready <= _GEN_0;
      if (_GEN_0) axi_araddr <= S_AXI_ARADDR;
      axi_rdata <= _mmap_regs_MMAP_read_data;
      axi_rvalid <=
        ~axi_rvalid & axi_arready & S_AXI_ARVALID | ~(axi_rvalid & S_AXI_RREADY)
        & axi_rvalid;
    end
  end  // always @(posedge)
  mmap_regs_32x32_r4 mmap_regs (
      .clock          (clock),
      .reset          (reset),
      .MMAP_write_en  (axi_awready & S_AXI_AWVALID & ~axi_bvalid),
      .MMAP_write_addr(axi_awaddr),
      .MMAP_write_data(S_AXI_WDATA),
      .MMAP_read_en   (axi_arready & S_AXI_ARVALID & ~axi_rvalid),
      .MMAP_read_addr (axi_araddr),
      .MMAP_read_data (_mmap_regs_MMAP_read_data)
  );
  assign S_AXI_AWREADY = axi_awready;
  assign S_AXI_WREADY  = axi_wready;
  assign S_AXI_BVALID  = axi_bvalid;
  assign S_AXI_ARREADY = axi_arready;
  assign S_AXI_RDATA   = axi_rdata;
  assign S_AXI_RVALID  = axi_rvalid;
endmodule

module ram_32x32_s8_b131072 (
    input         clock,
    reset,
    RAM_write_en,
    input  [31:0] RAM_write_addr,
    RAM_write_data,
    input         RAM_read_en,
    input  [31:0] RAM_read_addr,
    output [31:0] RAM_read_data,
    output        RAM_read_resp
);

  reg [31:0] ram_0;
  reg [31:0] ram_1;
  reg [31:0] ram_2;
  reg [31:0] ram_3;
  reg [31:0] ram_4;
  reg [31:0] ram_5;
  reg [31:0] ram_6;
  reg [31:0] ram_7;
  wire [31:0] _aw_offset_addr_T = RAM_write_addr - 32'h20000;
  wire [31:0] _ar_offset_addr_T = RAM_read_addr - 32'h20000;
  wire ar_valid = (|(RAM_read_addr[31:17])) & _ar_offset_addr_T < 32'h20;
  wire [2:0]  _mem_addr_T_3 =
    RAM_read_en ? _ar_offset_addr_T[4:2] : RAM_write_en ? _aw_offset_addr_T[4:2] : 3'h0;
  reg [31:0] casez_tmp;
  always_comb begin
    casez (_mem_addr_T_3)
      3'b000:  casez_tmp = ram_0;
      3'b001:  casez_tmp = ram_1;
      3'b010:  casez_tmp = ram_2;
      3'b011:  casez_tmp = ram_3;
      3'b100:  casez_tmp = ram_4;
      3'b101:  casez_tmp = ram_5;
      3'b110:  casez_tmp = ram_6;
      default: casez_tmp = ram_7;
    endcase
  end  // always_comb
  wire _GEN = RAM_write_en & (|(RAM_write_addr[31:17])) & _aw_offset_addr_T < 32'h20;
  always @(posedge clock) begin
    if (reset) begin
      ram_0 <= 32'h0;
      ram_1 <= 32'h0;
      ram_2 <= 32'h0;
      ram_3 <= 32'h0;
      ram_4 <= 32'h0;
      ram_5 <= 32'h0;
      ram_6 <= 32'h0;
      ram_7 <= 32'h0;
    end else begin
      if (_GEN & _mem_addr_T_3 == 3'h0) ram_0 <= RAM_write_data;
      if (_GEN & _mem_addr_T_3 == 3'h1) ram_1 <= RAM_write_data;
      if (_GEN & _mem_addr_T_3 == 3'h2) ram_2 <= RAM_write_data;
      if (_GEN & _mem_addr_T_3 == 3'h3) ram_3 <= RAM_write_data;
      if (_GEN & _mem_addr_T_3 == 3'h4) ram_4 <= RAM_write_data;
      if (_GEN & _mem_addr_T_3 == 3'h5) ram_5 <= RAM_write_data;
      if (_GEN & _mem_addr_T_3 == 3'h6) ram_6 <= RAM_write_data;
      if (_GEN & (&_mem_addr_T_3)) ram_7 <= RAM_write_data;
    end
  end  // always @(posedge)
  assign RAM_read_data = RAM_read_en & ar_valid ? casez_tmp : 32'h0;
  assign RAM_read_resp = ar_valid;
endmodule

module axifull_slave_ram_32x32_i4_u1_s8_b131072 (
    input         clock,
    reset,
    input  [31:0] S_AXI_AWADDR,
    input         S_AXI_AWVALID,
    output        S_AXI_AWREADY,
    input  [31:0] S_AXI_WDATA,
    input         S_AXI_WVALID,
    output        S_AXI_WREADY,
    input         S_AXI_BREADY,
    output        S_AXI_BVALID,
    input  [31:0] S_AXI_ARADDR,
    input         S_AXI_ARVALID,
    output        S_AXI_ARREADY,
    input         S_AXI_RREADY,
    output [31:0] S_AXI_RDATA,
    output        S_AXI_RVALID
);

  wire [31:0] _mmap_region_RAM_read_data;
  wire        _mmap_region_RAM_read_resp;
  reg         axi_awready;
  reg         axi_awv_awr_flag;
  reg  [31:0] axi_awaddr;
  reg  [ 1:0] axi_awburst;
  reg  [ 7:0] axi_awlen_cntr;
  reg         axi_wready;
  reg         axi_bvalid;
  reg         axi_arready;
  reg  [31:0] axi_araddr;
  reg  [ 1:0] axi_arburst;
  reg  [ 7:0] axi_arlen_cntr;
  reg         axi_arv_arr_flag;
  reg         axi_rvalid;
  reg  [31:0] casez_tmp;
  always_comb begin
    casez (axi_awburst)
      2'b00:   casez_tmp = axi_awaddr;
      2'b01:   casez_tmp = {axi_awaddr[31:2] + 30'h1, 2'h0};
      2'b10:   casez_tmp = axi_awaddr;
      default: casez_tmp = {2'h0, axi_awaddr[31:2] + 30'h1};
    endcase
  end  // always_comb
  reg [31:0] casez_tmp_0;
  always_comb begin
    casez (axi_arburst)
      2'b00:   casez_tmp_0 = axi_araddr;
      2'b01:   casez_tmp_0 = {axi_araddr[31:2] + 30'h1, 2'h0};
      2'b10:   casez_tmp_0 = axi_araddr;
      default: casez_tmp_0 = {2'h0, S_AXI_ARADDR[31:2] + 30'h1};
    endcase
  end  // always_comb
  wire _GEN = ~axi_awready & S_AXI_AWVALID & ~axi_awv_awr_flag;
  wire _GEN_0 = _GEN & ~axi_arv_arr_flag;
  wire _GEN_1 = ~axi_arready & S_AXI_ARVALID;
  wire _GEN_2 = _GEN_1 & ~axi_awv_awr_flag & ~axi_arv_arr_flag;
  wire _GEN_3 = axi_rvalid & S_AXI_RREADY;
  wire _GEN_4 = axi_arlen_cntr == 8'h0;
  wire _GEN_5 = _GEN_3 & _GEN_4;
  always @(posedge clock) begin
    if (reset) begin
      axi_awready <= 1'h0;
      axi_awv_awr_flag <= 1'h0;
      axi_awaddr <= 32'h0;
      axi_awburst <= 2'h0;
      axi_awlen_cntr <= 8'h0;
      axi_wready <= 1'h0;
      axi_bvalid <= 1'h0;
      axi_arready <= 1'h0;
      axi_araddr <= 32'h0;
      axi_arburst <= 2'h0;
      axi_arlen_cntr <= 8'h0;
      axi_arv_arr_flag <= 1'h0;
      axi_rvalid <= 1'h0;
    end else begin
      axi_awready <= _GEN_0 | axi_wready & axi_awready;
      axi_awv_awr_flag <= _GEN_0 | ~axi_wready & axi_awv_awr_flag;
      if (_GEN) begin
        axi_awaddr <= S_AXI_AWADDR;
        axi_awburst <= 2'h1;
        axi_awlen_cntr <= 8'h0;
      end else if (axi_awlen_cntr == 8'h0 & axi_wready & S_AXI_WVALID) begin
        axi_awaddr <= casez_tmp;
        axi_awlen_cntr <= axi_awlen_cntr + 8'h1;
      end
      axi_wready <= ~axi_wready & S_AXI_WVALID & axi_awv_awr_flag;
      axi_bvalid <=
        axi_awv_awr_flag & axi_wready & S_AXI_WVALID & ~axi_bvalid
        | ~(S_AXI_BREADY & axi_bvalid) & axi_bvalid;
      axi_arready <= _GEN_2 | _GEN_5 & axi_arready;
      if (_GEN_1 & ~axi_arv_arr_flag) begin
        axi_araddr <= S_AXI_ARADDR;
        axi_arburst <= 2'h1;
        axi_arlen_cntr <= 8'h0;
      end else if (_GEN_4 & axi_rvalid & S_AXI_RREADY) begin
        axi_araddr <= casez_tmp_0;
        axi_arlen_cntr <= axi_arlen_cntr + 8'h1;
      end
      axi_arv_arr_flag <= _GEN_2 | ~_GEN_5 & axi_arv_arr_flag;
      axi_rvalid <= axi_arv_arr_flag & ~axi_rvalid | ~_GEN_3 & axi_rvalid;
    end
  end  // always @(posedge)
  ram_32x32_s8_b131072 mmap_region (
      .clock         (clock),
      .reset         (reset),
      .RAM_write_en  (axi_wready & S_AXI_WVALID),
      .RAM_write_addr(axi_awaddr),
      .RAM_write_data(S_AXI_WDATA),
      .RAM_read_en   (axi_arv_arr_flag),
      .RAM_read_addr (axi_araddr),
      .RAM_read_data (_mmap_region_RAM_read_data),
      .RAM_read_resp (_mmap_region_RAM_read_resp)
  );
  assign S_AXI_AWREADY = axi_awready;
  assign S_AXI_WREADY = axi_wready;
  assign S_AXI_BVALID = axi_bvalid;
  assign S_AXI_ARREADY = axi_arready;
  assign S_AXI_RDATA = axi_rvalid & _mmap_region_RAM_read_resp ? _mmap_region_RAM_read_data : 32'h0;
  assign S_AXI_RVALID = axi_rvalid;
endmodule

module acm2108_wrapper (
    input         clock,
    reset,
    input  [31:0] S_AXI_AWADDR,
    input         S_AXI_AWVALID,
    output        S_AXI_AWREADY,
    input  [31:0] S_AXI_WDATA,
    input         S_AXI_WVALID,
    output        S_AXI_WREADY,
    S_AXI_BVALID,
    input         S_AXI_BREADY,
    input  [31:0] S_AXI_ARADDR,
    input         S_AXI_ARVALID,
    output        S_AXI_ARREADY,
    output [31:0] S_AXI_RDATA,
    output        S_AXI_RVALID,
    input         S_AXI_RREADY,
    output [ 1:0] acm_led,
    input         acm_key_in,
    input  [ 7:0] acm_AD0,
    acm_AD1,
    output        acm_AD0_CLK,
    acm_AD1_CLK,
    output [ 7:0] acm_DA0_Data,
    acm_DA1_Data,
    output        acm_DA0_Clk,
    acm_DA1_Clk,
    output [13:0] acm_ddr_addr,
    output [ 2:0] acm_ddr_ba,
    output        acm_ddr_cs_n,
    acm_ddr_ras_n,
    acm_ddr_cas_n,
    acm_ddr_we_n,
    acm_ddr_clk,
    acm_ddr_clk_n,
    acm_ddr_cke,
    acm_ddr_odt,
    acm_ddr_reset_n,
    output [ 1:0] acm_ddr_dqm,
    inout  [15:0] acm_ddr_dq,
    inout  [ 1:0] acm_ddr_dqs,
    acm_ddr_dqs_n,
    input         acm_rgmii_rx_clk_i,
    input  [ 3:0] acm_rgmii_rxd,
    input         acm_rgmii_rxdv,
    output        acm_eth_rst_n,
    acm_eth_mdc,
    acm_eth_mdio,
    acm_rgmii_tx_clk,
    output [ 3:0] acm_rgmii_txd,
    output        acm_rgmii_txen
);

  wire [ 1:0] _acm2108_led;
  reg  [ 7:0] regChannelSel;
  reg  [31:0] regDataNum;
  reg  [31:0] regAdcSpeed;
  reg         regRestartReq;
  reg  [ 2:0] regDdsWaveSel;
  reg  [31:0] regDdsFtw;
  reg         regDdsRestart;
  reg  [15:0] regLocalMacHi;
  reg  [31:0] regLocalMacLo;
  reg  [31:0] regLocalIp;
  reg  [15:0] regLocalPort;
  reg         axi_awready;
  reg  [31:0] axi_awaddr;
  reg         axi_wready;
  reg         axi_bvalid;
  reg         axi_arready;
  reg  [31:0] axi_araddr;
  reg  [31:0] axi_rdata;
  reg         axi_rvalid;
  wire [31:0] _raddr_T = axi_araddr - 32'h30000;
  wire        _GEN = ~axi_awready & S_AXI_AWVALID;
  wire        _GEN_0 = ~axi_bvalid & axi_wready & S_AXI_WVALID;
  wire        _GEN_1 = axi_awaddr[7:0] == 8'h8;
  wire        _GEN_2 = axi_awaddr[7:0] == 8'hC;
  wire        _GEN_3 = axi_awaddr[7:0] == 8'h10;
  wire        _GEN_4 = axi_awaddr[7:0] == 8'h14;
  wire        _GEN_5 = axi_awaddr[7:0] == 8'h1C;
  wire        _GEN_6 = axi_awaddr[7:0] == 8'h20;
  wire        _GEN_7 = axi_awaddr[7:0] == 8'h18;
  wire        _GEN_8 = axi_awaddr[7:0] == 8'h24;
  wire [15:0] _GEN_9 = {S_AXI_WDATA[15:8], 8'h0};
  wire        _GEN_10 = axi_awaddr[7:0] == 8'h28;
  wire        _GEN_11 = axi_awaddr[7:0] == 8'h2C;
  wire        _GEN_12 = ~axi_arready & S_AXI_ARVALID;
  wire        _GEN_13 = ~axi_rvalid & axi_arready & S_AXI_ARVALID;
  always @(posedge clock) begin
    if (reset) begin
      regChannelSel <= 8'h0;
      regDataNum <= 32'h400;
      regAdcSpeed <= 32'h1;
      regRestartReq <= 1'h0;
      regDdsWaveSel <= 3'h0;
      regDdsFtw <= 32'h0;
      regDdsRestart <= 1'h0;
      regLocalMacHi <= 16'hA;
      regLocalMacLo <= 32'h3501FEC0;
      regLocalIp <= 32'hC0A80002;
      regLocalPort <= 16'h1388;
      axi_awready <= 1'h0;
      axi_awaddr <= 32'h0;
      axi_wready <= 1'h0;
      axi_bvalid <= 1'h0;
      axi_arready <= 1'h0;
      axi_araddr <= 32'h0;
      axi_rdata <= 32'h0;
      axi_rvalid <= 1'h0;
    end else begin
      if (_GEN_0 & _GEN_1) regChannelSel <= S_AXI_WDATA[7:0];
      if (~_GEN_0 | _GEN_1 | ~_GEN_2) begin
      end else regDataNum <= regDataNum & 32'hFFFFFF | {S_AXI_WDATA[31:24], 24'h0};
      if (~_GEN_0 | _GEN_1 | _GEN_2 | ~_GEN_3) begin
      end else regAdcSpeed <= regAdcSpeed & 32'hFFFFFF | {S_AXI_WDATA[31:24], 24'h0};
      regRestartReq <= _GEN_0 & ~(_GEN_1 | _GEN_2 | _GEN_3) & _GEN_4 & S_AXI_WDATA[0];
      if (~_GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | ~_GEN_5) begin
      end else regDdsWaveSel <= S_AXI_WDATA[2:0];
      if (~_GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | ~_GEN_6) begin
      end else regDdsFtw <= regDdsFtw & 32'hFFFFFF | {S_AXI_WDATA[31:24], 24'h0};
      regDdsRestart <=
        _GEN_0 & ~(_GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6) & _GEN_7
        & S_AXI_WDATA[0];
      if (~_GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | ~_GEN_8) begin
      end else regLocalMacHi <= regLocalMacHi & 16'hFF | _GEN_9;
      if (~_GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
          | ~_GEN_10) begin
      end else regLocalMacLo <= regLocalMacLo & 32'hFFFFFF | {S_AXI_WDATA[31:24], 24'h0};
      if (~_GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
          | _GEN_10 | ~_GEN_11) begin
      end else regLocalIp <= regLocalIp & 32'hFFFFFF | {S_AXI_WDATA[31:24], 24'h0};
      if (~_GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
          | _GEN_10 | _GEN_11 | axi_awaddr[7:0] != 8'h30) begin
      end else regLocalPort <= regLocalPort & 16'hFF | _GEN_9;
      axi_awready <= _GEN;
      if (_GEN) axi_awaddr <= S_AXI_AWADDR;
      axi_wready <=
        ~axi_wready & axi_awready & S_AXI_AWVALID | ~(axi_wready & S_AXI_WVALID)
        & axi_wready;
      axi_bvalid <= _GEN_0 | ~(S_AXI_BREADY & axi_bvalid) & axi_bvalid;
      axi_arready <= _GEN_12;
      if (_GEN_12) axi_araddr <= S_AXI_ARADDR;
      if (_GEN_13)
        axi_rdata <=
          _raddr_T == 32'h34
            ? {31'h0, _acm2108_led[1]}
            : _raddr_T == 32'h30
                ? {16'h0, regLocalPort}
                : _raddr_T == 32'h2C
                    ? regLocalIp
                    : _raddr_T == 32'h28
                        ? regLocalMacLo
                        : _raddr_T == 32'h24
                            ? {16'h0, regLocalMacHi}
                            : _raddr_T == 32'h20
                                ? regDdsFtw
                                : _raddr_T == 32'h1C
                                    ? {29'h0, regDdsWaveSel}
                                    : _raddr_T == 32'h10
                                        ? regAdcSpeed
                                        : _raddr_T == 32'hC
                                            ? regDataNum
                                            : _raddr_T == 32'h8
                                                ? {24'h0, regChannelSel}
                                                : _raddr_T == 32'h4
                                                    ? {30'h0, _acm2108_led}
                                                    : _raddr_T == 32'h0
                                                        ? {31'h0, regRestartReq}
                                                        : 32'h0;
      axi_rvalid <= _GEN_13 | ~(axi_rvalid & S_AXI_RREADY) & axi_rvalid;
    end
  end  // always @(posedge)
  acm2108_ddr3_udp acm2108 (
      .clk                    (clock),
      .reset_n                (~reset),
      .ChannelSel             (regChannelSel),
      .DataNum                (regDataNum),
      .ADC_Speed_Set          (regAdcSpeed),
      .RestartReq             (regRestartReq),
      .RestartReq_DDS         (regDdsRestart),
      .DDS_WaveSel            (regDdsWaveSel),
      .DDS_FTW                (regDdsFtw),
      .LOCAL_MAC              ({regLocalMacHi, regLocalMacLo}),
      .LOCAL_IP               (regLocalIp),
      .LOCAL_PORT             (regLocalPort),
      .led                    (_acm2108_led),
      .external_led           (acm_led),
      .external_key_in        (acm_key_in),
      .external_AD0           (acm_AD0),
      .external_AD1           (acm_AD1),
      .external_AD0_CLK       (acm_AD0_CLK),
      .external_AD1_CLK       (acm_AD1_CLK),
      .external_DA0_Data      (acm_DA0_Data),
      .external_DA1_Data      (acm_DA1_Data),
      .external_DA0_Clk       (acm_DA0_Clk),
      .external_DA1_Clk       (acm_DA1_Clk),
      .external_ddr_addr      (acm_ddr_addr),
      .external_ddr_ba        (acm_ddr_ba),
      .external_ddr_cs_n      (acm_ddr_cs_n),
      .external_ddr_ras_n     (acm_ddr_ras_n),
      .external_ddr_cas_n     (acm_ddr_cas_n),
      .external_ddr_we_n      (acm_ddr_we_n),
      .external_ddr_clk       (acm_ddr_clk),
      .external_ddr_clk_n     (acm_ddr_clk_n),
      .external_ddr_cke       (acm_ddr_cke),
      .external_ddr_odt       (acm_ddr_odt),
      .external_ddr_reset_n   (acm_ddr_reset_n),
      .external_ddr_dqm       (acm_ddr_dqm),
      .external_ddr_dq        (acm_ddr_dq),
      .external_ddr_dqs       (acm_ddr_dqs),
      .external_ddr_dqs_n     (acm_ddr_dqs_n),
      .external_rgmii_rx_clk_i(acm_rgmii_rx_clk_i),
      .external_rgmii_rxd     (acm_rgmii_rxd),
      .external_rgmii_rxdv    (acm_rgmii_rxdv),
      .external_eth_rst_n     (acm_eth_rst_n),
      .external_eth_mdc       (acm_eth_mdc),
      .external_eth_mdio      (acm_eth_mdio),
      .external_rgmii_tx_clk  (acm_rgmii_tx_clk),
      .external_rgmii_txd     (acm_rgmii_txd),
      .external_rgmii_txen    (acm_rgmii_txen)
  );
  assign S_AXI_AWREADY = axi_awready;
  assign S_AXI_WREADY  = axi_wready;
  assign S_AXI_BVALID  = axi_bvalid;
  assign S_AXI_ARREADY = axi_arready;
  assign S_AXI_RDATA   = axi_rdata;
  assign S_AXI_RVALID  = axi_rvalid;
endmodule

module signal_measure_wrapper (
    input         clock,
    reset,
    input  [31:0] S_AXI_AWADDR,
    input         S_AXI_AWVALID,
    output        S_AXI_AWREADY,
    input  [31:0] S_AXI_WDATA,
    input         S_AXI_WVALID,
    output        S_AXI_WREADY,
    S_AXI_BVALID,
    input         S_AXI_BREADY,
    input  [31:0] S_AXI_ARADDR,
    input         S_AXI_ARVALID,
    output        S_AXI_ARREADY,
    output [31:0] S_AXI_RDATA,
    output        S_AXI_RVALID,
    input         S_AXI_RREADY,
    sig_in
);

  wire        _signalMeasure_busy;
  wire        _signalMeasure_finish;
  wire [25:0] _signalMeasure_period_out;
  wire [ 7:0] _signalMeasure_duty;
  wire [19:0] _signalMeasure_high_time;
  wire [19:0] _signalMeasure_low_time;
  reg         regEnable;
  reg         axi_awready;
  reg  [31:0] axi_awaddr;
  reg         axi_wready;
  reg         axi_bvalid;
  reg         axi_arready;
  reg  [31:0] axi_araddr;
  reg  [31:0] axi_rdata;
  reg         axi_rvalid;
  wire [31:0] _raddr_T = axi_araddr - 32'h40000;
  wire        _GEN = ~axi_awready & S_AXI_AWVALID;
  wire        _GEN_0 = ~axi_bvalid & axi_wready & S_AXI_WVALID;
  wire        _GEN_1 = ~axi_arready & S_AXI_ARVALID;
  wire        _GEN_2 = ~axi_rvalid & axi_arready & S_AXI_ARVALID;
  always @(posedge clock) begin
    if (reset) begin
      regEnable   <= 1'h0;
      axi_awready <= 1'h0;
      axi_awaddr  <= 32'h0;
      axi_wready  <= 1'h0;
      axi_bvalid  <= 1'h0;
      axi_arready <= 1'h0;
      axi_araddr  <= 32'h0;
      axi_rdata   <= 32'h0;
      axi_rvalid  <= 1'h0;
    end else begin
      regEnable <=
        _GEN_0 & axi_awaddr - 32'h40000 == 32'h0
          ? S_AXI_WDATA[0]
          : ~(regEnable & _signalMeasure_busy) & regEnable;
      axi_awready <= _GEN;
      if (_GEN) axi_awaddr <= S_AXI_AWADDR;
      axi_wready <=
        ~axi_wready & axi_awready & S_AXI_AWVALID | ~(axi_wready & S_AXI_WVALID)
        & axi_wready;
      axi_bvalid <= _GEN_0 | ~(S_AXI_BREADY & axi_bvalid) & axi_bvalid;
      axi_arready <= _GEN_1;
      if (_GEN_1) axi_araddr <= S_AXI_ARADDR;
      if (_GEN_2)
        axi_rdata <=
          _raddr_T == 32'h14
            ? {12'h0, _signalMeasure_low_time}
            : _raddr_T == 32'h10
                ? {12'h0, _signalMeasure_high_time}
                : _raddr_T == 32'hC
                    ? {24'h0, _signalMeasure_duty}
                    : _raddr_T == 32'h8
                        ? {6'h0, _signalMeasure_period_out}
                        : _raddr_T == 32'h4
                            ? {30'h0, _signalMeasure_finish, _signalMeasure_busy}
                            : _raddr_T == 32'h0 ? {31'h0, regEnable} : 32'h0;
      axi_rvalid <= _GEN_2 | ~(axi_rvalid & S_AXI_RREADY) & axi_rvalid;
    end
  end  // always @(posedge)
  signal_measure_ctrl signalMeasure (
      .clk       (clock),
      .rst_n     (~reset),
      .enable    (regEnable),
      .sig_in    (sig_in),
      .busy      (_signalMeasure_busy),
      .finish    (_signalMeasure_finish),
      .period_out(_signalMeasure_period_out),
      .duty      (_signalMeasure_duty),
      .high_time (_signalMeasure_high_time),
      .low_time  (_signalMeasure_low_time)
  );
  assign S_AXI_AWREADY = axi_awready;
  assign S_AXI_WREADY  = axi_wready;
  assign S_AXI_BVALID  = axi_bvalid;
  assign S_AXI_ARREADY = axi_arready;
  assign S_AXI_RDATA   = axi_rdata;
  assign S_AXI_RVALID  = axi_rvalid;
endmodule

module axi_cmd_test_module (
    input         clock,
    reset,
    output        TXD,
    input         RXD,
    output [ 1:0] acm_led,
    input         acm_key_in,
    input  [ 7:0] acm_AD0,
    acm_AD1,
    output        acm_AD0_CLK,
    acm_AD1_CLK,
    output [ 7:0] acm_DA0_Data,
    acm_DA1_Data,
    output        acm_DA0_Clk,
    acm_DA1_Clk,
    output [13:0] acm_ddr_addr,
    output [ 2:0] acm_ddr_ba,
    output        acm_ddr_cs_n,
    acm_ddr_ras_n,
    acm_ddr_cas_n,
    acm_ddr_we_n,
    acm_ddr_clk,
    acm_ddr_clk_n,
    acm_ddr_cke,
    acm_ddr_odt,
    acm_ddr_reset_n,
    output [ 1:0] acm_ddr_dqm,
    inout  [15:0] acm_ddr_dq,
    inout  [ 1:0] acm_ddr_dqs,
    acm_ddr_dqs_n,
    input         acm_rgmii_rx_clk_i,
    input  [ 3:0] acm_rgmii_rxd,
    input         acm_rgmii_rxdv,
    output        acm_eth_rst_n,
    acm_eth_mdc,
    acm_eth_mdio,
    acm_rgmii_tx_clk,
    output [ 3:0] acm_rgmii_txd,
    output        acm_rgmii_txen,
    acm_interrupt,
    input         sig_in
);

  wire        _slave4_S_AXI_AWREADY;
  wire        _slave4_S_AXI_WREADY;
  wire        _slave4_S_AXI_BVALID;
  wire        _slave4_S_AXI_ARREADY;
  wire [31:0] _slave4_S_AXI_RDATA;
  wire        _slave4_S_AXI_RVALID;
  wire        _slave3_S_AXI_AWREADY;
  wire        _slave3_S_AXI_WREADY;
  wire        _slave3_S_AXI_BVALID;
  wire        _slave3_S_AXI_ARREADY;
  wire [31:0] _slave3_S_AXI_RDATA;
  wire        _slave3_S_AXI_RVALID;
  wire        _slave2_S_AXI_AWREADY;
  wire        _slave2_S_AXI_WREADY;
  wire        _slave2_S_AXI_BVALID;
  wire        _slave2_S_AXI_ARREADY;
  wire [31:0] _slave2_S_AXI_RDATA;
  wire        _slave2_S_AXI_RVALID;
  wire        _slave1_S_AXI_AWREADY;
  wire        _slave1_S_AXI_WREADY;
  wire        _slave1_S_AXI_BVALID;
  wire        _slave1_S_AXI_ARREADY;
  wire [31:0] _slave1_S_AXI_RDATA;
  wire        _slave1_S_AXI_RVALID;
  wire        _interconnect_S_AXI_AWREADY;
  wire        _interconnect_S_AXI_WREADY;
  wire        _interconnect_S_AXI_BVALID;
  wire        _interconnect_S_AXI_ARREADY;
  wire [31:0] _interconnect_S_AXI_RDATA;
  wire        _interconnect_S_AXI_RVALID;
  wire [31:0] _interconnect_M_AXI_0_AWADDR;
  wire        _interconnect_M_AXI_0_AWVALID;
  wire [31:0] _interconnect_M_AXI_0_WDATA;
  wire        _interconnect_M_AXI_0_WVALID;
  wire        _interconnect_M_AXI_0_BREADY;
  wire [31:0] _interconnect_M_AXI_0_ARADDR;
  wire        _interconnect_M_AXI_0_ARVALID;
  wire        _interconnect_M_AXI_0_RREADY;
  wire [31:0] _interconnect_M_AXI_1_AWADDR;
  wire        _interconnect_M_AXI_1_AWVALID;
  wire [31:0] _interconnect_M_AXI_1_WDATA;
  wire        _interconnect_M_AXI_1_WVALID;
  wire        _interconnect_M_AXI_1_BREADY;
  wire [31:0] _interconnect_M_AXI_1_ARADDR;
  wire        _interconnect_M_AXI_1_ARVALID;
  wire        _interconnect_M_AXI_1_RREADY;
  wire [31:0] _interconnect_M_AXI_2_AWADDR;
  wire        _interconnect_M_AXI_2_AWVALID;
  wire [31:0] _interconnect_M_AXI_2_WDATA;
  wire        _interconnect_M_AXI_2_WVALID;
  wire        _interconnect_M_AXI_2_BREADY;
  wire [31:0] _interconnect_M_AXI_2_ARADDR;
  wire        _interconnect_M_AXI_2_ARVALID;
  wire        _interconnect_M_AXI_2_RREADY;
  wire [31:0] _interconnect_M_AXI_3_AWADDR;
  wire        _interconnect_M_AXI_3_AWVALID;
  wire [31:0] _interconnect_M_AXI_3_WDATA;
  wire        _interconnect_M_AXI_3_WVALID;
  wire        _interconnect_M_AXI_3_BREADY;
  wire [31:0] _interconnect_M_AXI_3_ARADDR;
  wire        _interconnect_M_AXI_3_ARVALID;
  wire        _interconnect_M_AXI_3_RREADY;
  wire        _lite2fullBridge_S_AXI_AWREADY;
  wire        _lite2fullBridge_S_AXI_WREADY;
  wire        _lite2fullBridge_S_AXI_BVALID;
  wire        _lite2fullBridge_S_AXI_ARREADY;
  wire [31:0] _lite2fullBridge_S_AXI_RDATA;
  wire        _lite2fullBridge_S_AXI_RVALID;
  wire [31:0] _lite2fullBridge_M_AXI_AWADDR;
  wire        _lite2fullBridge_M_AXI_AWVALID;
  wire [31:0] _lite2fullBridge_M_AXI_WDATA;
  wire        _lite2fullBridge_M_AXI_WVALID;
  wire        _lite2fullBridge_M_AXI_BREADY;
  wire [31:0] _lite2fullBridge_M_AXI_ARADDR;
  wire        _lite2fullBridge_M_AXI_ARVALID;
  wire        _lite2fullBridge_M_AXI_RREADY;
  wire [31:0] _master_M_AXI_AWADDR;
  wire        _master_M_AXI_AWVALID;
  wire [31:0] _master_M_AXI_WDATA;
  wire        _master_M_AXI_WVALID;
  wire        _master_M_AXI_BREADY;
  wire [31:0] _master_M_AXI_ARADDR;
  wire        _master_M_AXI_ARVALID;
  wire        _master_M_AXI_RREADY;
  axilite_master_uart_cmd_32x32_b115200_f50000000 master (
      .clock        (clock),
      .reset        (reset),
      .M_AXI_AWADDR (_master_M_AXI_AWADDR),
      .M_AXI_AWVALID(_master_M_AXI_AWVALID),
      .M_AXI_AWREADY(_interconnect_S_AXI_AWREADY),
      .M_AXI_WDATA  (_master_M_AXI_WDATA),
      .M_AXI_WVALID (_master_M_AXI_WVALID),
      .M_AXI_WREADY (_interconnect_S_AXI_WREADY),
      .M_AXI_BVALID (_interconnect_S_AXI_BVALID),
      .M_AXI_BREADY (_master_M_AXI_BREADY),
      .M_AXI_ARADDR (_master_M_AXI_ARADDR),
      .M_AXI_ARVALID(_master_M_AXI_ARVALID),
      .M_AXI_ARREADY(_interconnect_S_AXI_ARREADY),
      .M_AXI_RDATA  (_interconnect_S_AXI_RDATA),
      .M_AXI_RVALID (_interconnect_S_AXI_RVALID),
      .M_AXI_RREADY (_master_M_AXI_RREADY),
      .TX           (TXD),
      .RX           (RXD)
  );
  axi_lite2full_32x32_i4_u1 lite2fullBridge (
      .S_AXI_AWADDR (_interconnect_M_AXI_1_AWADDR),
      .S_AXI_AWVALID(_interconnect_M_AXI_1_AWVALID),
      .S_AXI_AWREADY(_lite2fullBridge_S_AXI_AWREADY),
      .S_AXI_WDATA  (_interconnect_M_AXI_1_WDATA),
      .S_AXI_WVALID (_interconnect_M_AXI_1_WVALID),
      .S_AXI_WREADY (_lite2fullBridge_S_AXI_WREADY),
      .S_AXI_BVALID (_lite2fullBridge_S_AXI_BVALID),
      .S_AXI_BREADY (_interconnect_M_AXI_1_BREADY),
      .S_AXI_ARADDR (_interconnect_M_AXI_1_ARADDR),
      .S_AXI_ARVALID(_interconnect_M_AXI_1_ARVALID),
      .S_AXI_ARREADY(_lite2fullBridge_S_AXI_ARREADY),
      .S_AXI_RDATA  (_lite2fullBridge_S_AXI_RDATA),
      .S_AXI_RVALID (_lite2fullBridge_S_AXI_RVALID),
      .S_AXI_RREADY (_interconnect_M_AXI_1_RREADY),
      .M_AXI_AWADDR (_lite2fullBridge_M_AXI_AWADDR),
      .M_AXI_AWVALID(_lite2fullBridge_M_AXI_AWVALID),
      .M_AXI_AWREADY(_slave2_S_AXI_AWREADY),
      .M_AXI_WDATA  (_lite2fullBridge_M_AXI_WDATA),
      .M_AXI_WVALID (_lite2fullBridge_M_AXI_WVALID),
      .M_AXI_WREADY (_slave2_S_AXI_WREADY),
      .M_AXI_BREADY (_lite2fullBridge_M_AXI_BREADY),
      .M_AXI_BVALID (_slave2_S_AXI_BVALID),
      .M_AXI_ARADDR (_lite2fullBridge_M_AXI_ARADDR),
      .M_AXI_ARVALID(_lite2fullBridge_M_AXI_ARVALID),
      .M_AXI_ARREADY(_slave2_S_AXI_ARREADY),
      .M_AXI_RREADY (_lite2fullBridge_M_AXI_RREADY),
      .M_AXI_RDATA  (_slave2_S_AXI_RDATA),
      .M_AXI_RVALID (_slave2_S_AXI_RVALID)
  );
  axilite_interconnect4_32x32 interconnect_0 (
      .S_AXI_AWADDR   (_master_M_AXI_AWADDR),
      .S_AXI_AWVALID  (_master_M_AXI_AWVALID),
      .S_AXI_AWREADY  (_interconnect_S_AXI_AWREADY),
      .S_AXI_WDATA    (_master_M_AXI_WDATA),
      .S_AXI_WVALID   (_master_M_AXI_WVALID),
      .S_AXI_WREADY   (_interconnect_S_AXI_WREADY),
      .S_AXI_BVALID   (_interconnect_S_AXI_BVALID),
      .S_AXI_BREADY   (_master_M_AXI_BREADY),
      .S_AXI_ARADDR   (_master_M_AXI_ARADDR),
      .S_AXI_ARVALID  (_master_M_AXI_ARVALID),
      .S_AXI_ARREADY  (_interconnect_S_AXI_ARREADY),
      .S_AXI_RDATA    (_interconnect_S_AXI_RDATA),
      .S_AXI_RVALID   (_interconnect_S_AXI_RVALID),
      .S_AXI_RREADY   (_master_M_AXI_RREADY),
      .M_AXI_0_AWADDR (_interconnect_M_AXI_0_AWADDR),
      .M_AXI_0_AWVALID(_interconnect_M_AXI_0_AWVALID),
      .M_AXI_0_AWREADY(_slave1_S_AXI_AWREADY),
      .M_AXI_0_WDATA  (_interconnect_M_AXI_0_WDATA),
      .M_AXI_0_WVALID (_interconnect_M_AXI_0_WVALID),
      .M_AXI_0_WREADY (_slave1_S_AXI_WREADY),
      .M_AXI_0_BVALID (_slave1_S_AXI_BVALID),
      .M_AXI_0_BREADY (_interconnect_M_AXI_0_BREADY),
      .M_AXI_0_ARADDR (_interconnect_M_AXI_0_ARADDR),
      .M_AXI_0_ARVALID(_interconnect_M_AXI_0_ARVALID),
      .M_AXI_0_ARREADY(_slave1_S_AXI_ARREADY),
      .M_AXI_0_RDATA  (_slave1_S_AXI_RDATA),
      .M_AXI_0_RVALID (_slave1_S_AXI_RVALID),
      .M_AXI_0_RREADY (_interconnect_M_AXI_0_RREADY),
      .M_AXI_1_AWADDR (_interconnect_M_AXI_1_AWADDR),
      .M_AXI_1_AWVALID(_interconnect_M_AXI_1_AWVALID),
      .M_AXI_1_AWREADY(_lite2fullBridge_S_AXI_AWREADY),
      .M_AXI_1_WDATA  (_interconnect_M_AXI_1_WDATA),
      .M_AXI_1_WVALID (_interconnect_M_AXI_1_WVALID),
      .M_AXI_1_WREADY (_lite2fullBridge_S_AXI_WREADY),
      .M_AXI_1_BVALID (_lite2fullBridge_S_AXI_BVALID),
      .M_AXI_1_BREADY (_interconnect_M_AXI_1_BREADY),
      .M_AXI_1_ARADDR (_interconnect_M_AXI_1_ARADDR),
      .M_AXI_1_ARVALID(_interconnect_M_AXI_1_ARVALID),
      .M_AXI_1_ARREADY(_lite2fullBridge_S_AXI_ARREADY),
      .M_AXI_1_RDATA  (_lite2fullBridge_S_AXI_RDATA),
      .M_AXI_1_RVALID (_lite2fullBridge_S_AXI_RVALID),
      .M_AXI_1_RREADY (_interconnect_M_AXI_1_RREADY),
      .M_AXI_2_AWADDR (_interconnect_M_AXI_2_AWADDR),
      .M_AXI_2_AWVALID(_interconnect_M_AXI_2_AWVALID),
      .M_AXI_2_AWREADY(_slave3_S_AXI_AWREADY),
      .M_AXI_2_WDATA  (_interconnect_M_AXI_2_WDATA),
      .M_AXI_2_WVALID (_interconnect_M_AXI_2_WVALID),
      .M_AXI_2_WREADY (_slave3_S_AXI_WREADY),
      .M_AXI_2_BVALID (_slave3_S_AXI_BVALID),
      .M_AXI_2_BREADY (_interconnect_M_AXI_2_BREADY),
      .M_AXI_2_ARADDR (_interconnect_M_AXI_2_ARADDR),
      .M_AXI_2_ARVALID(_interconnect_M_AXI_2_ARVALID),
      .M_AXI_2_ARREADY(_slave3_S_AXI_ARREADY),
      .M_AXI_2_RDATA  (_slave3_S_AXI_RDATA),
      .M_AXI_2_RVALID (_slave3_S_AXI_RVALID),
      .M_AXI_2_RREADY (_interconnect_M_AXI_2_RREADY),
      .M_AXI_3_AWADDR (_interconnect_M_AXI_3_AWADDR),
      .M_AXI_3_AWVALID(_interconnect_M_AXI_3_AWVALID),
      .M_AXI_3_AWREADY(_slave4_S_AXI_AWREADY),
      .M_AXI_3_WDATA  (_interconnect_M_AXI_3_WDATA),
      .M_AXI_3_WVALID (_interconnect_M_AXI_3_WVALID),
      .M_AXI_3_WREADY (_slave4_S_AXI_WREADY),
      .M_AXI_3_BVALID (_slave4_S_AXI_BVALID),
      .M_AXI_3_BREADY (_interconnect_M_AXI_3_BREADY),
      .M_AXI_3_ARADDR (_interconnect_M_AXI_3_ARADDR),
      .M_AXI_3_ARVALID(_interconnect_M_AXI_3_ARVALID),
      .M_AXI_3_ARREADY(_slave4_S_AXI_ARREADY),
      .M_AXI_3_RDATA  (_slave4_S_AXI_RDATA),
      .M_AXI_3_RVALID (_slave4_S_AXI_RVALID),
      .M_AXI_3_RREADY (_interconnect_M_AXI_3_RREADY)
  );
  axilite_slave_mmap_32x32_r4 slave1 (
      .clock        (clock),
      .reset        (reset),
      .S_AXI_AWADDR (_interconnect_M_AXI_0_AWADDR),
      .S_AXI_AWVALID(_interconnect_M_AXI_0_AWVALID),
      .S_AXI_AWREADY(_slave1_S_AXI_AWREADY),
      .S_AXI_WDATA  (_interconnect_M_AXI_0_WDATA),
      .S_AXI_WVALID (_interconnect_M_AXI_0_WVALID),
      .S_AXI_WREADY (_slave1_S_AXI_WREADY),
      .S_AXI_BVALID (_slave1_S_AXI_BVALID),
      .S_AXI_BREADY (_interconnect_M_AXI_0_BREADY),
      .S_AXI_ARADDR (_interconnect_M_AXI_0_ARADDR),
      .S_AXI_ARVALID(_interconnect_M_AXI_0_ARVALID),
      .S_AXI_ARREADY(_slave1_S_AXI_ARREADY),
      .S_AXI_RDATA  (_slave1_S_AXI_RDATA),
      .S_AXI_RVALID (_slave1_S_AXI_RVALID),
      .S_AXI_RREADY (_interconnect_M_AXI_0_RREADY)
  );
  axifull_slave_ram_32x32_i4_u1_s8_b131072 slave2 (
      .clock        (clock),
      .reset        (reset),
      .S_AXI_AWADDR (_lite2fullBridge_M_AXI_AWADDR),
      .S_AXI_AWVALID(_lite2fullBridge_M_AXI_AWVALID),
      .S_AXI_AWREADY(_slave2_S_AXI_AWREADY),
      .S_AXI_WDATA  (_lite2fullBridge_M_AXI_WDATA),
      .S_AXI_WVALID (_lite2fullBridge_M_AXI_WVALID),
      .S_AXI_WREADY (_slave2_S_AXI_WREADY),
      .S_AXI_BREADY (_lite2fullBridge_M_AXI_BREADY),
      .S_AXI_BVALID (_slave2_S_AXI_BVALID),
      .S_AXI_ARADDR (_lite2fullBridge_M_AXI_ARADDR),
      .S_AXI_ARVALID(_lite2fullBridge_M_AXI_ARVALID),
      .S_AXI_ARREADY(_slave2_S_AXI_ARREADY),
      .S_AXI_RREADY (_lite2fullBridge_M_AXI_RREADY),
      .S_AXI_RDATA  (_slave2_S_AXI_RDATA),
      .S_AXI_RVALID (_slave2_S_AXI_RVALID)
  );
  acm2108_wrapper slave3 (
      .clock             (clock),
      .reset             (reset),
      .S_AXI_AWADDR      (_interconnect_M_AXI_2_AWADDR),
      .S_AXI_AWVALID     (_interconnect_M_AXI_2_AWVALID),
      .S_AXI_AWREADY     (_slave3_S_AXI_AWREADY),
      .S_AXI_WDATA       (_interconnect_M_AXI_2_WDATA),
      .S_AXI_WVALID      (_interconnect_M_AXI_2_WVALID),
      .S_AXI_WREADY      (_slave3_S_AXI_WREADY),
      .S_AXI_BVALID      (_slave3_S_AXI_BVALID),
      .S_AXI_BREADY      (_interconnect_M_AXI_2_BREADY),
      .S_AXI_ARADDR      (_interconnect_M_AXI_2_ARADDR),
      .S_AXI_ARVALID     (_interconnect_M_AXI_2_ARVALID),
      .S_AXI_ARREADY     (_slave3_S_AXI_ARREADY),
      .S_AXI_RDATA       (_slave3_S_AXI_RDATA),
      .S_AXI_RVALID      (_slave3_S_AXI_RVALID),
      .S_AXI_RREADY      (_interconnect_M_AXI_2_RREADY),
      .acm_led           (acm_led),
      .acm_key_in        (acm_key_in),
      .acm_AD0           (acm_AD0),
      .acm_AD1           (acm_AD1),
      .acm_AD0_CLK       (acm_AD0_CLK),
      .acm_AD1_CLK       (acm_AD1_CLK),
      .acm_DA0_Data      (acm_DA0_Data),
      .acm_DA1_Data      (acm_DA1_Data),
      .acm_DA0_Clk       (acm_DA0_Clk),
      .acm_DA1_Clk       (acm_DA1_Clk),
      .acm_ddr_addr      (acm_ddr_addr),
      .acm_ddr_ba        (acm_ddr_ba),
      .acm_ddr_cs_n      (acm_ddr_cs_n),
      .acm_ddr_ras_n     (acm_ddr_ras_n),
      .acm_ddr_cas_n     (acm_ddr_cas_n),
      .acm_ddr_we_n      (acm_ddr_we_n),
      .acm_ddr_clk       (acm_ddr_clk),
      .acm_ddr_clk_n     (acm_ddr_clk_n),
      .acm_ddr_cke       (acm_ddr_cke),
      .acm_ddr_odt       (acm_ddr_odt),
      .acm_ddr_reset_n   (acm_ddr_reset_n),
      .acm_ddr_dqm       (acm_ddr_dqm),
      .acm_ddr_dq        (acm_ddr_dq),
      .acm_ddr_dqs       (acm_ddr_dqs),
      .acm_ddr_dqs_n     (acm_ddr_dqs_n),
      .acm_rgmii_rx_clk_i(acm_rgmii_rx_clk_i),
      .acm_rgmii_rxd     (acm_rgmii_rxd),
      .acm_rgmii_rxdv    (acm_rgmii_rxdv),
      .acm_eth_rst_n     (acm_eth_rst_n),
      .acm_eth_mdc       (acm_eth_mdc),
      .acm_eth_mdio      (acm_eth_mdio),
      .acm_rgmii_tx_clk  (acm_rgmii_tx_clk),
      .acm_rgmii_txd     (acm_rgmii_txd),
      .acm_rgmii_txen    (acm_rgmii_txen)
  );
  signal_measure_wrapper slave4 (
      .clock        (clock),
      .reset        (reset),
      .S_AXI_AWADDR (_interconnect_M_AXI_3_AWADDR),
      .S_AXI_AWVALID(_interconnect_M_AXI_3_AWVALID),
      .S_AXI_AWREADY(_slave4_S_AXI_AWREADY),
      .S_AXI_WDATA  (_interconnect_M_AXI_3_WDATA),
      .S_AXI_WVALID (_interconnect_M_AXI_3_WVALID),
      .S_AXI_WREADY (_slave4_S_AXI_WREADY),
      .S_AXI_BVALID (_slave4_S_AXI_BVALID),
      .S_AXI_BREADY (_interconnect_M_AXI_3_BREADY),
      .S_AXI_ARADDR (_interconnect_M_AXI_3_ARADDR),
      .S_AXI_ARVALID(_interconnect_M_AXI_3_ARVALID),
      .S_AXI_ARREADY(_slave4_S_AXI_ARREADY),
      .S_AXI_RDATA  (_slave4_S_AXI_RDATA),
      .S_AXI_RVALID (_slave4_S_AXI_RVALID),
      .S_AXI_RREADY (_interconnect_M_AXI_3_RREADY),
      .sig_in       (sig_in)
  );
  assign acm_interrupt = 1'h0;
endmodule
