`timescale 1ns / 1ps
// Generated by CIRCT firtool-1.62.1-1-gdf5ed6ea5
module axilite_master_rw_32x32(
  input         clock,
                reset,
  output [31:0] M_AXI_AWADDR,
  output        M_AXI_AWVALID,
  input         M_AXI_AWREADY,
  output [31:0] M_AXI_WDATA,
  output        M_AXI_WVALID,
  input         M_AXI_WREADY,
  input  [1:0]  M_AXI_BRESP,
  input         M_AXI_BVALID,
  output        M_AXI_BREADY,
  output [31:0] M_AXI_ARADDR,
  output        M_AXI_ARVALID,
  input         M_AXI_ARREADY,
  input  [31:0] M_AXI_RDATA,
  input  [1:0]  M_AXI_RRESP,
  input         M_AXI_RVALID,
  output        M_AXI_RREADY,
  input  [31:0] W_DATA,
                W_ADDR,
  input         W_EN,
  output        W_DONE,
  output [1:0]  W_RESP,
  output [31:0] R_DATA,
  input  [31:0] R_ADDR,
  input         R_EN,
  output        R_DONE,
  output [1:0]  R_RESP,
  output        BUSY
);

  reg  [2:0]  state;
  reg  [31:0] axi_awaddr;
  reg         axi_awvalid;
  reg  [31:0] axi_wdata;
  reg         axi_wvalid;
  reg         axi_bready;
  reg  [31:0] axi_araddr;
  reg         axi_arvalid;
  reg         axi_rready;
  wire        _GEN = state == 3'h0;
  wire        _GEN_0 = state == 3'h1;
  wire        _GEN_1 = state == 3'h2;
  wire        _GEN_2 = state == 3'h3;
  wire        _GEN_3 = _GEN_2 & M_AXI_BVALID;
  wire        _GEN_4 = _GEN | _GEN_0 | _GEN_1;
  wire        _GEN_5 = state == 3'h4;
  wire        _GEN_6 = state == 3'h5;
  wire        _GEN_7 = _GEN_6 & M_AXI_RVALID;
  reg  [2:0]  casez_tmp;
  wire [2:0]  _GEN_8 = _GEN_7 ? 3'h0 : state;
  always_comb begin
    casez (state)
      3'b000:
        casez_tmp = W_EN ? 3'h1 : R_EN ? 3'h4 : state;
      3'b001:
        casez_tmp = M_AXI_AWREADY ? 3'h2 : state;
      3'b010:
        casez_tmp = M_AXI_WREADY ? 3'h3 : state;
      3'b011:
        casez_tmp = M_AXI_BVALID ? 3'h0 : state;
      3'b100:
        casez_tmp = M_AXI_ARREADY ? 3'h5 : state;
      3'b101:
        casez_tmp = _GEN_8;
      3'b110:
        casez_tmp = _GEN_8;
      default:
        casez_tmp = _GEN_8;
    endcase
  end // always_comb
  wire        _GEN_9 = _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_5;
  wire        _GEN_10 = _GEN_0 | _GEN_1 | _GEN_2;
  always @(posedge clock) begin
    if (reset) begin
      state <= 3'h0;
      axi_awaddr <= 32'h0;
      axi_awvalid <= 1'h0;
      axi_wdata <= 32'h0;
      axi_wvalid <= 1'h0;
      axi_bready <= 1'h0;
      axi_araddr <= 32'h0;
      axi_arvalid <= 1'h0;
      axi_rready <= 1'h0;
    end
    else begin
      state <= casez_tmp;
      if (_GEN & W_EN) begin
        axi_awaddr <= W_ADDR;
        axi_wdata <= W_DATA;
      end
      if (_GEN) begin
        axi_awvalid <= W_EN;
        axi_arvalid <= ~W_EN & R_EN;
      end
      else begin
        axi_awvalid <= ~(_GEN_0 & M_AXI_AWREADY) & axi_awvalid;
        axi_arvalid <= (_GEN_10 | ~(_GEN_5 & M_AXI_ARREADY)) & axi_arvalid;
      end
      axi_wvalid <=
        ~_GEN
        & (_GEN_0 ? M_AXI_AWREADY | axi_wvalid : ~(_GEN_1 & M_AXI_WREADY) & axi_wvalid);
      axi_bready <=
        ~_GEN
        & (_GEN_0
             ? axi_bready
             : _GEN_1 ? M_AXI_WREADY | axi_bready : ~_GEN_3 & axi_bready);
      if (~_GEN | W_EN | ~R_EN) begin
      end
      else
        axi_araddr <= R_ADDR;
      axi_rready <=
        ~_GEN
        & (_GEN_10
             ? axi_rready
             : _GEN_5 ? M_AXI_ARREADY | axi_rready : ~_GEN_7 & axi_rready);
    end
  end // always @(posedge)
  assign M_AXI_AWADDR = axi_awaddr;
  assign M_AXI_AWVALID = axi_awvalid;
  assign M_AXI_WDATA = axi_wdata;
  assign M_AXI_WVALID = axi_wvalid;
  assign M_AXI_BREADY = axi_bready;
  assign M_AXI_ARADDR = axi_araddr;
  assign M_AXI_ARVALID = axi_arvalid;
  assign M_AXI_RREADY = axi_rready;
  assign W_DONE = ~_GEN_4 & _GEN_2 & M_AXI_BVALID;
  assign W_RESP = _GEN_4 | ~_GEN_3 ? 2'h0 : M_AXI_BRESP;
  assign R_DATA = M_AXI_RDATA;
  assign R_DONE = ~_GEN_9 & _GEN_6 & M_AXI_RVALID;
  assign R_RESP = _GEN_9 | ~_GEN_7 ? 2'h0 : M_AXI_RRESP;
  assign BUSY = |state;
endmodule

module axi_lite2full_32x32_i4_u1(
  output        S_AXI_aw_ready,
  input         S_AXI_aw_valid,
  input  [31:0] S_AXI_aw_bits_addr,
  output        S_AXI_w_ready,
  input         S_AXI_w_valid,
  input  [31:0] S_AXI_w_bits_data,
  input         S_AXI_b_ready,
  output        S_AXI_b_valid,
  output [1:0]  S_AXI_b_bits_resp,
  output        S_AXI_ar_ready,
  input         S_AXI_ar_valid,
  input  [31:0] S_AXI_ar_bits_addr,
  input         S_AXI_r_ready,
  output        S_AXI_r_valid,
  output [31:0] S_AXI_r_bits_data,
  output [1:0]  S_AXI_r_bits_resp,
  input         M_AXI_aw_ready,
  output        M_AXI_aw_valid,
  output [31:0] M_AXI_aw_bits_addr,
  input         M_AXI_w_ready,
  output        M_AXI_w_valid,
  output [31:0] M_AXI_w_bits_data,
  output        M_AXI_b_ready,
  input         M_AXI_b_valid,
  input  [1:0]  M_AXI_b_bits_resp,
  input         M_AXI_ar_ready,
  output        M_AXI_ar_valid,
  output [31:0] M_AXI_ar_bits_addr,
  output        M_AXI_r_ready,
  input         M_AXI_r_valid,
  input  [31:0] M_AXI_r_bits_data,
  input  [1:0]  M_AXI_r_bits_resp
);

  assign S_AXI_aw_ready = M_AXI_aw_ready;
  assign S_AXI_w_ready = M_AXI_w_ready;
  assign S_AXI_b_valid = M_AXI_b_valid;
  assign S_AXI_b_bits_resp = M_AXI_b_bits_resp;
  assign S_AXI_ar_ready = M_AXI_ar_ready;
  assign S_AXI_r_valid = M_AXI_r_valid;
  assign S_AXI_r_bits_data = M_AXI_r_bits_data;
  assign S_AXI_r_bits_resp = M_AXI_r_bits_resp;
  assign M_AXI_aw_valid = S_AXI_aw_valid;
  assign M_AXI_aw_bits_addr = S_AXI_aw_bits_addr;
  assign M_AXI_w_valid = S_AXI_w_valid;
  assign M_AXI_w_bits_data = S_AXI_w_bits_data;
  assign M_AXI_b_ready = S_AXI_b_ready;
  assign M_AXI_ar_valid = S_AXI_ar_valid;
  assign M_AXI_ar_bits_addr = S_AXI_ar_bits_addr;
  assign M_AXI_r_ready = S_AXI_r_ready;
endmodule

module axilite_interconnect2_32x32(
  output        S_AXI_aw_ready,
  input         S_AXI_aw_valid,
  input  [31:0] S_AXI_aw_bits_addr,
  output        S_AXI_w_ready,
  input         S_AXI_w_valid,
  input  [31:0] S_AXI_w_bits_data,
  input         S_AXI_b_ready,
  output        S_AXI_b_valid,
  output [1:0]  S_AXI_b_bits_resp,
  output        S_AXI_ar_ready,
  input         S_AXI_ar_valid,
  input  [31:0] S_AXI_ar_bits_addr,
  input         S_AXI_r_ready,
  output        S_AXI_r_valid,
  output [31:0] S_AXI_r_bits_data,
  output [1:0]  S_AXI_r_bits_resp,
  input         M0_AXI_aw_ready,
  output        M0_AXI_aw_valid,
  output [31:0] M0_AXI_aw_bits_addr,
  input         M0_AXI_w_ready,
  output        M0_AXI_w_valid,
  output [31:0] M0_AXI_w_bits_data,
  output        M0_AXI_b_ready,
  input         M0_AXI_b_valid,
  input  [1:0]  M0_AXI_b_bits_resp,
  input         M0_AXI_ar_ready,
  output        M0_AXI_ar_valid,
  output [31:0] M0_AXI_ar_bits_addr,
  output        M0_AXI_r_ready,
  input         M0_AXI_r_valid,
  input  [31:0] M0_AXI_r_bits_data,
  input  [1:0]  M0_AXI_r_bits_resp,
  input         M1_AXI_aw_ready,
  output        M1_AXI_aw_valid,
  output [31:0] M1_AXI_aw_bits_addr,
  input         M1_AXI_w_ready,
  output        M1_AXI_w_valid,
  output [31:0] M1_AXI_w_bits_data,
  output        M1_AXI_b_ready,
  input         M1_AXI_b_valid,
  input  [1:0]  M1_AXI_b_bits_resp,
  input         M1_AXI_ar_ready,
  output        M1_AXI_ar_valid,
  output [31:0] M1_AXI_ar_bits_addr,
  output        M1_AXI_r_ready,
  input         M1_AXI_r_valid,
  input  [31:0] M1_AXI_r_bits_data,
  input  [1:0]  M1_AXI_r_bits_resp
);

  wire _S_AXI_b_bits_T_11 = S_AXI_aw_bits_addr < 32'h30000;
  wire _S_AXI_r_bits_T_11 = S_AXI_ar_bits_addr < 32'h30000;
  wire S_AXI_r_bits_slaveSelect = (|(S_AXI_ar_bits_addr[31:17])) & _S_AXI_r_bits_T_11;
  wire S_AXI_r_bits_slaveSelect_1 = (|(S_AXI_ar_bits_addr[31:17])) & _S_AXI_r_bits_T_11;
  assign S_AXI_aw_ready =
    ~((|(S_AXI_aw_bits_addr[31:17])) & _S_AXI_b_bits_T_11) & M0_AXI_aw_ready
    | (|(S_AXI_aw_bits_addr[31:17])) & _S_AXI_b_bits_T_11 & M1_AXI_aw_ready;
  assign S_AXI_w_ready =
    ~((|(S_AXI_aw_bits_addr[31:17])) & _S_AXI_b_bits_T_11) & M0_AXI_w_ready
    | (|(S_AXI_aw_bits_addr[31:17])) & _S_AXI_b_bits_T_11 & M1_AXI_w_ready;
  assign S_AXI_b_valid =
    ~((|(S_AXI_aw_bits_addr[31:17])) & _S_AXI_b_bits_T_11) & M0_AXI_b_valid
    | (|(S_AXI_aw_bits_addr[31:17])) & _S_AXI_b_bits_T_11 & M1_AXI_b_valid;
  assign S_AXI_b_bits_resp =
    ((|(S_AXI_aw_bits_addr[31:17])) & _S_AXI_b_bits_T_11 ? 2'h0 : M0_AXI_b_bits_resp)
    | ((|(S_AXI_aw_bits_addr[31:17])) & _S_AXI_b_bits_T_11 ? M1_AXI_b_bits_resp : 2'h0);
  assign S_AXI_ar_ready =
    ~((|(S_AXI_ar_bits_addr[31:17])) & _S_AXI_r_bits_T_11) & M0_AXI_ar_ready
    | (|(S_AXI_ar_bits_addr[31:17])) & _S_AXI_r_bits_T_11 & M1_AXI_ar_ready;
  assign S_AXI_r_valid =
    ~((|(S_AXI_ar_bits_addr[31:17])) & _S_AXI_r_bits_T_11) & M0_AXI_r_valid
    | (|(S_AXI_ar_bits_addr[31:17])) & _S_AXI_r_bits_T_11 & M1_AXI_r_valid;
  assign S_AXI_r_bits_data =
    (S_AXI_r_bits_slaveSelect ? 32'h0 : M0_AXI_r_bits_data)
    | (S_AXI_r_bits_slaveSelect_1 ? M1_AXI_r_bits_data : 32'h0);
  assign S_AXI_r_bits_resp =
    (S_AXI_r_bits_slaveSelect ? 2'h0 : M0_AXI_r_bits_resp)
    | (S_AXI_r_bits_slaveSelect_1 ? M1_AXI_r_bits_resp : 2'h0);
  assign M0_AXI_aw_valid =
    S_AXI_aw_valid & ~((|(S_AXI_aw_bits_addr[31:17])) & _S_AXI_b_bits_T_11);
  assign M0_AXI_aw_bits_addr = S_AXI_aw_bits_addr;
  assign M0_AXI_w_valid =
    S_AXI_w_valid & ~((|(S_AXI_aw_bits_addr[31:17])) & _S_AXI_b_bits_T_11);
  assign M0_AXI_w_bits_data = S_AXI_w_bits_data;
  assign M0_AXI_b_ready =
    S_AXI_b_ready & ~((|(S_AXI_aw_bits_addr[31:17])) & _S_AXI_b_bits_T_11);
  assign M0_AXI_ar_valid =
    S_AXI_ar_valid & ~((|(S_AXI_ar_bits_addr[31:17])) & _S_AXI_r_bits_T_11);
  assign M0_AXI_ar_bits_addr = S_AXI_ar_bits_addr;
  assign M0_AXI_r_ready =
    S_AXI_r_ready & ~((|(S_AXI_ar_bits_addr[31:17])) & _S_AXI_r_bits_T_11);
  assign M1_AXI_aw_valid =
    S_AXI_aw_valid & (|(S_AXI_aw_bits_addr[31:17])) & _S_AXI_b_bits_T_11;
  assign M1_AXI_aw_bits_addr = S_AXI_aw_bits_addr;
  assign M1_AXI_w_valid =
    S_AXI_w_valid & (|(S_AXI_aw_bits_addr[31:17])) & _S_AXI_b_bits_T_11;
  assign M1_AXI_w_bits_data = S_AXI_w_bits_data;
  assign M1_AXI_b_ready =
    S_AXI_b_ready & (|(S_AXI_aw_bits_addr[31:17])) & _S_AXI_b_bits_T_11;
  assign M1_AXI_ar_valid =
    S_AXI_ar_valid & (|(S_AXI_ar_bits_addr[31:17])) & _S_AXI_r_bits_T_11;
  assign M1_AXI_ar_bits_addr = S_AXI_ar_bits_addr;
  assign M1_AXI_r_ready =
    S_AXI_r_ready & (|(S_AXI_ar_bits_addr[31:17])) & _S_AXI_r_bits_T_11;
endmodule

module mmap_regs_32x32_r4(
  input         clock,
                reset,
                MMAP_write_en,
  input  [31:0] MMAP_write_addr,
                MMAP_write_data,
  input         MMAP_read_en,
  input  [31:0] MMAP_read_addr,
  output [31:0] MMAP_read_data,
  output        MMAP_read_resp
);

  reg  [31:0] regs_0;
  reg  [31:0] regs_1;
  reg  [31:0] regs_2;
  reg  [31:0] regs_3;
  wire        read_addr_match =
    MMAP_read_addr == 32'h10000 | MMAP_read_addr == 32'h14000
    | MMAP_read_addr == 32'h18000 | MMAP_read_addr == 32'h1C000;
  wire        _GEN =
    MMAP_write_en
    & (MMAP_write_addr == 32'h10000 | MMAP_write_addr == 32'h14000
       | MMAP_write_addr == 32'h18000 | MMAP_write_addr == 32'h1C000);
  always @(posedge clock) begin
    if (reset) begin
      regs_0 <= 32'h0;
      regs_1 <= 32'h0;
      regs_2 <= 32'h0;
      regs_3 <= 32'h0;
    end
    else begin
      if (_GEN & MMAP_write_addr == 32'h10000)
        regs_0 <= MMAP_write_data;
      if (_GEN & MMAP_write_addr == 32'h14000)
        regs_1 <= MMAP_write_data;
      if (_GEN & MMAP_write_addr == 32'h18000)
        regs_2 <= MMAP_write_data;
      if (_GEN & MMAP_write_addr == 32'h1C000)
        regs_3 <= MMAP_write_data;
    end
  end // always @(posedge)
  assign MMAP_read_data =
    MMAP_read_en & read_addr_match
      ? (MMAP_read_addr == 32'h10000
           ? regs_0
           : MMAP_read_addr == 32'h14000
               ? regs_1
               : MMAP_read_addr == 32'h18000
                   ? regs_2
                   : MMAP_read_addr == 32'h1C000 ? regs_3 : 32'h0)
      : 32'h0;
  assign MMAP_read_resp = read_addr_match;
endmodule

module axilite_slave_mmap_32x32_r4(
  input         clock,
                reset,
  input  [31:0] S_AXI_AWADDR,
  input         S_AXI_AWVALID,
  output        S_AXI_AWREADY,
  input  [31:0] S_AXI_WDATA,
  input         S_AXI_WVALID,
  output        S_AXI_WREADY,
  output [1:0]  S_AXI_BRESP,
  output        S_AXI_BVALID,
  input         S_AXI_BREADY,
  input  [31:0] S_AXI_ARADDR,
  input         S_AXI_ARVALID,
  output        S_AXI_ARREADY,
  output [31:0] S_AXI_RDATA,
  output [1:0]  S_AXI_RRESP,
  output        S_AXI_RVALID,
  input         S_AXI_RREADY
);

  wire [31:0] _mmap_regs_MMAP_read_data;
  wire        _mmap_regs_MMAP_read_resp;
  reg         axi_awready;
  reg  [31:0] axi_awaddr;
  reg         axi_wready;
  reg         axi_bvalid;
  reg  [1:0]  axi_bresp;
  reg         axi_arready;
  reg  [31:0] axi_araddr;
  reg  [31:0] axi_rdata;
  reg         axi_rvalid;
  reg  [1:0]  axi_rresp;
  wire        _GEN = ~axi_awready & S_AXI_AWVALID;
  wire        _GEN_0 = ~axi_bvalid & axi_wready & S_AXI_WVALID;
  wire        _GEN_1 = ~axi_arready & S_AXI_ARVALID;
  wire        _GEN_2 = ~axi_rvalid & axi_arready & S_AXI_ARVALID;
  always @(posedge clock) begin
    if (reset) begin
      axi_awready <= 1'h0;
      axi_awaddr <= 32'h0;
      axi_wready <= 1'h0;
      axi_bvalid <= 1'h0;
      axi_bresp <= 2'h0;
      axi_arready <= 1'h0;
      axi_araddr <= 32'h0;
      axi_rdata <= 32'h0;
      axi_rvalid <= 1'h0;
      axi_rresp <= 2'h0;
    end
    else begin
      axi_awready <= _GEN;
      if (_GEN)
        axi_awaddr <= S_AXI_AWADDR;
      axi_wready <=
        ~axi_wready & axi_awready & S_AXI_AWVALID | ~(axi_wready & S_AXI_WVALID)
        & axi_wready;
      axi_bvalid <= _GEN_0 | ~(S_AXI_BREADY & axi_bvalid) & axi_bvalid;
      if (_GEN_0)
        axi_bresp <= {~_mmap_regs_MMAP_read_resp, 1'h0};
      axi_arready <= _GEN_1;
      if (_GEN_1)
        axi_araddr <= S_AXI_ARADDR;
      axi_rdata <= _mmap_regs_MMAP_read_data;
      axi_rvalid <= _GEN_2 | ~(axi_rvalid & S_AXI_RREADY) & axi_rvalid;
      if (_GEN_2)
        axi_rresp <= {~_mmap_regs_MMAP_read_resp, 1'h0};
    end
  end // always @(posedge)
  mmap_regs_32x32_r4 mmap_regs (
    .clock           (clock),
    .reset           (reset),
    .MMAP_write_en   (axi_awready & S_AXI_AWVALID & ~axi_bvalid),
    .MMAP_write_addr (axi_awaddr),
    .MMAP_write_data (S_AXI_WDATA),
    .MMAP_read_en    (axi_arready & S_AXI_ARVALID & ~axi_rvalid),
    .MMAP_read_addr  (axi_araddr),
    .MMAP_read_data  (_mmap_regs_MMAP_read_data),
    .MMAP_read_resp  (_mmap_regs_MMAP_read_resp)
  );
  assign S_AXI_AWREADY = axi_awready;
  assign S_AXI_WREADY = axi_wready;
  assign S_AXI_BRESP = axi_bresp;
  assign S_AXI_BVALID = axi_bvalid;
  assign S_AXI_ARREADY = axi_arready;
  assign S_AXI_RDATA = axi_rdata;
  assign S_AXI_RRESP = axi_rresp;
  assign S_AXI_RVALID = axi_rvalid;
endmodule

module ram_32x32_s8_b131072(
  input         clock,
                reset,
                RAM_write_en,
  input  [31:0] RAM_write_addr,
                RAM_write_data,
  output        RAM_write_resp,
  input         RAM_read_en,
  input  [31:0] RAM_read_addr,
  output [31:0] RAM_read_data,
  output        RAM_read_resp
);

  reg  [31:0] ram_0;
  reg  [31:0] ram_1;
  reg  [31:0] ram_2;
  reg  [31:0] ram_3;
  reg  [31:0] ram_4;
  reg  [31:0] ram_5;
  reg  [31:0] ram_6;
  reg  [31:0] ram_7;
  wire [31:0] _aw_offset_addr_T = RAM_write_addr - 32'h20000;
  wire [31:0] _ar_offset_addr_T = RAM_read_addr - 32'h20000;
  wire        aw_valid = (|(RAM_write_addr[31:17])) & _aw_offset_addr_T < 32'h20;
  wire        ar_valid = (|(RAM_read_addr[31:17])) & _ar_offset_addr_T < 32'h20;
  wire [2:0]  _mem_addr_T_3 =
    RAM_read_en ? _ar_offset_addr_T[4:2] : RAM_write_en ? _aw_offset_addr_T[4:2] : 3'h0;
  reg  [31:0] casez_tmp;
  always_comb begin
    casez (_mem_addr_T_3)
      3'b000:
        casez_tmp = ram_0;
      3'b001:
        casez_tmp = ram_1;
      3'b010:
        casez_tmp = ram_2;
      3'b011:
        casez_tmp = ram_3;
      3'b100:
        casez_tmp = ram_4;
      3'b101:
        casez_tmp = ram_5;
      3'b110:
        casez_tmp = ram_6;
      default:
        casez_tmp = ram_7;
    endcase
  end // always_comb
  wire        _GEN = RAM_write_en & aw_valid;
  always @(posedge clock) begin
    if (reset) begin
      ram_0 <= 32'h0;
      ram_1 <= 32'h0;
      ram_2 <= 32'h0;
      ram_3 <= 32'h0;
      ram_4 <= 32'h0;
      ram_5 <= 32'h0;
      ram_6 <= 32'h0;
      ram_7 <= 32'h0;
    end
    else begin
      if (_GEN & _mem_addr_T_3 == 3'h0)
        ram_0 <= RAM_write_data;
      if (_GEN & _mem_addr_T_3 == 3'h1)
        ram_1 <= RAM_write_data;
      if (_GEN & _mem_addr_T_3 == 3'h2)
        ram_2 <= RAM_write_data;
      if (_GEN & _mem_addr_T_3 == 3'h3)
        ram_3 <= RAM_write_data;
      if (_GEN & _mem_addr_T_3 == 3'h4)
        ram_4 <= RAM_write_data;
      if (_GEN & _mem_addr_T_3 == 3'h5)
        ram_5 <= RAM_write_data;
      if (_GEN & _mem_addr_T_3 == 3'h6)
        ram_6 <= RAM_write_data;
      if (_GEN & (&_mem_addr_T_3))
        ram_7 <= RAM_write_data;
    end
  end // always @(posedge)
  assign RAM_write_resp = aw_valid;
  assign RAM_read_data = RAM_read_en & ar_valid ? casez_tmp : 32'h0;
  assign RAM_read_resp = ar_valid;
endmodule

module axifull_slave_ram_32x32_i4_u1_s8_b131072(
  input         clock,
                reset,
  input  [31:0] S_AXI_AWADDR,
  input         S_AXI_AWVALID,
  output        S_AXI_AWREADY,
  input  [31:0] S_AXI_WDATA,
  input         S_AXI_WVALID,
  output        S_AXI_WREADY,
  input         S_AXI_BREADY,
  output [1:0]  S_AXI_BRESP,
  output        S_AXI_BVALID,
  input  [31:0] S_AXI_ARADDR,
  input         S_AXI_ARVALID,
  output        S_AXI_ARREADY,
  input         S_AXI_RREADY,
  output [31:0] S_AXI_RDATA,
  output [1:0]  S_AXI_RRESP,
  output        S_AXI_RVALID
);

  wire        _mmap_region_RAM_write_resp;
  wire [31:0] _mmap_region_RAM_read_data;
  wire        _mmap_region_RAM_read_resp;
  reg         axi_awready;
  reg         axi_awv_awr_flag;
  reg  [31:0] axi_awaddr;
  reg  [1:0]  axi_awburst;
  reg  [7:0]  axi_awlen_cntr;
  reg         axi_wready;
  reg         axi_bvalid;
  reg  [1:0]  axi_bresp;
  reg         axi_arready;
  reg  [31:0] axi_araddr;
  reg  [1:0]  axi_arburst;
  reg  [7:0]  axi_arlen_cntr;
  reg         axi_arv_arr_flag;
  reg         axi_rvalid;
  reg  [1:0]  axi_rresp;
  reg  [31:0] casez_tmp;
  always_comb begin
    casez (axi_awburst)
      2'b00:
        casez_tmp = axi_awaddr;
      2'b01:
        casez_tmp = {axi_awaddr[31:2] + 30'h1, 2'h0};
      2'b10:
        casez_tmp = axi_awaddr;
      default:
        casez_tmp = {2'h0, axi_awaddr[31:2] + 30'h1};
    endcase
  end // always_comb
  reg  [31:0] casez_tmp_0;
  always_comb begin
    casez (axi_arburst)
      2'b00:
        casez_tmp_0 = axi_araddr;
      2'b01:
        casez_tmp_0 = {axi_araddr[31:2] + 30'h1, 2'h0};
      2'b10:
        casez_tmp_0 = axi_araddr;
      default:
        casez_tmp_0 = {2'h0, S_AXI_ARADDR[31:2] + 30'h1};
    endcase
  end // always_comb
  wire        _GEN = ~axi_awready & S_AXI_AWVALID & ~axi_awv_awr_flag;
  wire        _GEN_0 = _GEN & ~axi_arv_arr_flag;
  wire        _GEN_1 = axi_awv_awr_flag & axi_wready & S_AXI_WVALID & ~axi_bvalid;
  wire        _GEN_2 = ~axi_arready & S_AXI_ARVALID;
  wire        _GEN_3 = _GEN_2 & ~axi_awv_awr_flag & ~axi_arv_arr_flag;
  wire        _GEN_4 = axi_rvalid & S_AXI_RREADY;
  wire        _GEN_5 = axi_arlen_cntr == 8'h0;
  wire        _GEN_6 = _GEN_4 & _GEN_5;
  wire        _GEN_7 = axi_arv_arr_flag & ~axi_rvalid;
  always @(posedge clock) begin
    if (reset) begin
      axi_awready <= 1'h0;
      axi_awv_awr_flag <= 1'h0;
      axi_awaddr <= 32'h0;
      axi_awburst <= 2'h0;
      axi_awlen_cntr <= 8'h0;
      axi_wready <= 1'h0;
      axi_bvalid <= 1'h0;
      axi_bresp <= 2'h0;
      axi_arready <= 1'h0;
      axi_araddr <= 32'h0;
      axi_arburst <= 2'h0;
      axi_arlen_cntr <= 8'h0;
      axi_arv_arr_flag <= 1'h0;
      axi_rvalid <= 1'h0;
      axi_rresp <= 2'h0;
    end
    else begin
      axi_awready <= _GEN_0 | axi_wready & axi_awready;
      axi_awv_awr_flag <= _GEN_0 | ~axi_wready & axi_awv_awr_flag;
      if (_GEN) begin
        axi_awaddr <= S_AXI_AWADDR;
        axi_awburst <= 2'h1;
        axi_awlen_cntr <= 8'h0;
      end
      else if (axi_awlen_cntr == 8'h0 & axi_wready & S_AXI_WVALID) begin
        axi_awaddr <= casez_tmp;
        axi_awlen_cntr <= axi_awlen_cntr + 8'h1;
      end
      axi_wready <= ~axi_wready & S_AXI_WVALID & axi_awv_awr_flag;
      axi_bvalid <= _GEN_1 | ~(S_AXI_BREADY & axi_bvalid) & axi_bvalid;
      if (_GEN_1)
        axi_bresp <= {~_mmap_region_RAM_write_resp, 1'h0};
      axi_arready <= _GEN_3 | _GEN_6 & axi_arready;
      if (_GEN_2 & ~axi_arv_arr_flag) begin
        axi_araddr <= S_AXI_ARADDR;
        axi_arburst <= 2'h1;
        axi_arlen_cntr <= 8'h0;
      end
      else if (_GEN_5 & axi_rvalid & S_AXI_RREADY) begin
        axi_araddr <= casez_tmp_0;
        axi_arlen_cntr <= axi_arlen_cntr + 8'h1;
      end
      axi_arv_arr_flag <= _GEN_3 | ~_GEN_6 & axi_arv_arr_flag;
      axi_rvalid <= _GEN_7 | ~_GEN_4 & axi_rvalid;
      if (_GEN_7)
        axi_rresp <= {~_mmap_region_RAM_read_resp, 1'h0};
    end
  end // always @(posedge)
  ram_32x32_s8_b131072 mmap_region (
    .clock          (clock),
    .reset          (reset),
    .RAM_write_en   (axi_wready & S_AXI_WVALID),
    .RAM_write_addr (axi_awaddr),
    .RAM_write_data (S_AXI_WDATA),
    .RAM_write_resp (_mmap_region_RAM_write_resp),
    .RAM_read_en    (axi_arv_arr_flag),
    .RAM_read_addr  (axi_araddr),
    .RAM_read_data  (_mmap_region_RAM_read_data),
    .RAM_read_resp  (_mmap_region_RAM_read_resp)
  );
  assign S_AXI_AWREADY = axi_awready;
  assign S_AXI_WREADY = axi_wready;
  assign S_AXI_BRESP = axi_bresp;
  assign S_AXI_BVALID = axi_bvalid;
  assign S_AXI_ARREADY = axi_arready;
  assign S_AXI_RDATA =
    axi_rvalid & _mmap_region_RAM_read_resp ? _mmap_region_RAM_read_data : 32'h0;
  assign S_AXI_RRESP = axi_rresp;
  assign S_AXI_RVALID = axi_rvalid;
endmodule

module axi_interconnect_and_bridge_test_module(
  input         clock,
                reset,
  input  [31:0] W_DATA,
                W_ADDR,
  input         W_EN,
  output        W_DONE,
  output [1:0]  W_RESP,
  output [31:0] R_DATA,
  input  [31:0] R_ADDR,
  input         R_EN,
  output        R_DONE,
  output [1:0]  R_RESP,
  output        BUSY
);

  wire        _slave2_S_AXI_AWREADY;
  wire        _slave2_S_AXI_WREADY;
  wire [1:0]  _slave2_S_AXI_BRESP;
  wire        _slave2_S_AXI_BVALID;
  wire        _slave2_S_AXI_ARREADY;
  wire [31:0] _slave2_S_AXI_RDATA;
  wire [1:0]  _slave2_S_AXI_RRESP;
  wire        _slave2_S_AXI_RVALID;
  wire        _slave1_S_AXI_AWREADY;
  wire        _slave1_S_AXI_WREADY;
  wire [1:0]  _slave1_S_AXI_BRESP;
  wire        _slave1_S_AXI_BVALID;
  wire        _slave1_S_AXI_ARREADY;
  wire [31:0] _slave1_S_AXI_RDATA;
  wire [1:0]  _slave1_S_AXI_RRESP;
  wire        _slave1_S_AXI_RVALID;
  wire        _interconnect_S_AXI_aw_ready;
  wire        _interconnect_S_AXI_w_ready;
  wire        _interconnect_S_AXI_b_valid;
  wire [1:0]  _interconnect_S_AXI_b_bits_resp;
  wire        _interconnect_S_AXI_ar_ready;
  wire        _interconnect_S_AXI_r_valid;
  wire [31:0] _interconnect_S_AXI_r_bits_data;
  wire [1:0]  _interconnect_S_AXI_r_bits_resp;
  wire        _interconnect_M0_AXI_aw_valid;
  wire [31:0] _interconnect_M0_AXI_aw_bits_addr;
  wire        _interconnect_M0_AXI_w_valid;
  wire [31:0] _interconnect_M0_AXI_w_bits_data;
  wire        _interconnect_M0_AXI_b_ready;
  wire        _interconnect_M0_AXI_ar_valid;
  wire [31:0] _interconnect_M0_AXI_ar_bits_addr;
  wire        _interconnect_M0_AXI_r_ready;
  wire        _interconnect_M1_AXI_aw_valid;
  wire [31:0] _interconnect_M1_AXI_aw_bits_addr;
  wire        _interconnect_M1_AXI_w_valid;
  wire [31:0] _interconnect_M1_AXI_w_bits_data;
  wire        _interconnect_M1_AXI_b_ready;
  wire        _interconnect_M1_AXI_ar_valid;
  wire [31:0] _interconnect_M1_AXI_ar_bits_addr;
  wire        _interconnect_M1_AXI_r_ready;
  wire        _lite2fullBridge_S_AXI_aw_ready;
  wire        _lite2fullBridge_S_AXI_w_ready;
  wire        _lite2fullBridge_S_AXI_b_valid;
  wire [1:0]  _lite2fullBridge_S_AXI_b_bits_resp;
  wire        _lite2fullBridge_S_AXI_ar_ready;
  wire        _lite2fullBridge_S_AXI_r_valid;
  wire [31:0] _lite2fullBridge_S_AXI_r_bits_data;
  wire [1:0]  _lite2fullBridge_S_AXI_r_bits_resp;
  wire        _lite2fullBridge_M_AXI_aw_valid;
  wire [31:0] _lite2fullBridge_M_AXI_aw_bits_addr;
  wire        _lite2fullBridge_M_AXI_w_valid;
  wire [31:0] _lite2fullBridge_M_AXI_w_bits_data;
  wire        _lite2fullBridge_M_AXI_b_ready;
  wire        _lite2fullBridge_M_AXI_ar_valid;
  wire [31:0] _lite2fullBridge_M_AXI_ar_bits_addr;
  wire        _lite2fullBridge_M_AXI_r_ready;
  wire [31:0] _master_M_AXI_AWADDR;
  wire        _master_M_AXI_AWVALID;
  wire [31:0] _master_M_AXI_WDATA;
  wire        _master_M_AXI_WVALID;
  wire        _master_M_AXI_BREADY;
  wire [31:0] _master_M_AXI_ARADDR;
  wire        _master_M_AXI_ARVALID;
  wire        _master_M_AXI_RREADY;
  wire [31:0] _master_R_DATA;
  wire        _master_R_DONE;
  reg  [31:0] read_data_reg;
  always @(posedge clock) begin
    if (reset)
      read_data_reg <= 32'h0;
    else if (_master_R_DONE)
      read_data_reg <= _master_R_DATA;
  end // always @(posedge)
  axilite_master_rw_32x32 master (
    .clock         (clock),
    .reset         (reset),
    .M_AXI_AWADDR  (_master_M_AXI_AWADDR),
    .M_AXI_AWVALID (_master_M_AXI_AWVALID),
    .M_AXI_AWREADY (_interconnect_S_AXI_aw_ready),
    .M_AXI_WDATA   (_master_M_AXI_WDATA),
    .M_AXI_WVALID  (_master_M_AXI_WVALID),
    .M_AXI_WREADY  (_interconnect_S_AXI_w_ready),
    .M_AXI_BRESP   (_interconnect_S_AXI_b_bits_resp),
    .M_AXI_BVALID  (_interconnect_S_AXI_b_valid),
    .M_AXI_BREADY  (_master_M_AXI_BREADY),
    .M_AXI_ARADDR  (_master_M_AXI_ARADDR),
    .M_AXI_ARVALID (_master_M_AXI_ARVALID),
    .M_AXI_ARREADY (_interconnect_S_AXI_ar_ready),
    .M_AXI_RDATA   (_interconnect_S_AXI_r_bits_data),
    .M_AXI_RRESP   (_interconnect_S_AXI_r_bits_resp),
    .M_AXI_RVALID  (_interconnect_S_AXI_r_valid),
    .M_AXI_RREADY  (_master_M_AXI_RREADY),
    .W_DATA        (W_DATA),
    .W_ADDR        (W_ADDR),
    .W_EN          (W_EN),
    .W_DONE        (W_DONE),
    .W_RESP        (W_RESP),
    .R_DATA        (_master_R_DATA),
    .R_ADDR        (R_ADDR),
    .R_EN          (R_EN),
    .R_DONE        (_master_R_DONE),
    .R_RESP        (R_RESP),
    .BUSY          (BUSY)
  );
  axi_lite2full_32x32_i4_u1 lite2fullBridge (
    .S_AXI_aw_ready     (_lite2fullBridge_S_AXI_aw_ready),
    .S_AXI_aw_valid     (_interconnect_M1_AXI_aw_valid),
    .S_AXI_aw_bits_addr (_interconnect_M1_AXI_aw_bits_addr),
    .S_AXI_w_ready      (_lite2fullBridge_S_AXI_w_ready),
    .S_AXI_w_valid      (_interconnect_M1_AXI_w_valid),
    .S_AXI_w_bits_data  (_interconnect_M1_AXI_w_bits_data),
    .S_AXI_b_ready      (_interconnect_M1_AXI_b_ready),
    .S_AXI_b_valid      (_lite2fullBridge_S_AXI_b_valid),
    .S_AXI_b_bits_resp  (_lite2fullBridge_S_AXI_b_bits_resp),
    .S_AXI_ar_ready     (_lite2fullBridge_S_AXI_ar_ready),
    .S_AXI_ar_valid     (_interconnect_M1_AXI_ar_valid),
    .S_AXI_ar_bits_addr (_interconnect_M1_AXI_ar_bits_addr),
    .S_AXI_r_ready      (_interconnect_M1_AXI_r_ready),
    .S_AXI_r_valid      (_lite2fullBridge_S_AXI_r_valid),
    .S_AXI_r_bits_data  (_lite2fullBridge_S_AXI_r_bits_data),
    .S_AXI_r_bits_resp  (_lite2fullBridge_S_AXI_r_bits_resp),
    .M_AXI_aw_ready     (_slave2_S_AXI_AWREADY),
    .M_AXI_aw_valid     (_lite2fullBridge_M_AXI_aw_valid),
    .M_AXI_aw_bits_addr (_lite2fullBridge_M_AXI_aw_bits_addr),
    .M_AXI_w_ready      (_slave2_S_AXI_WREADY),
    .M_AXI_w_valid      (_lite2fullBridge_M_AXI_w_valid),
    .M_AXI_w_bits_data  (_lite2fullBridge_M_AXI_w_bits_data),
    .M_AXI_b_ready      (_lite2fullBridge_M_AXI_b_ready),
    .M_AXI_b_valid      (_slave2_S_AXI_BVALID),
    .M_AXI_b_bits_resp  (_slave2_S_AXI_BRESP),
    .M_AXI_ar_ready     (_slave2_S_AXI_ARREADY),
    .M_AXI_ar_valid     (_lite2fullBridge_M_AXI_ar_valid),
    .M_AXI_ar_bits_addr (_lite2fullBridge_M_AXI_ar_bits_addr),
    .M_AXI_r_ready      (_lite2fullBridge_M_AXI_r_ready),
    .M_AXI_r_valid      (_slave2_S_AXI_RVALID),
    .M_AXI_r_bits_data  (_slave2_S_AXI_RDATA),
    .M_AXI_r_bits_resp  (_slave2_S_AXI_RRESP)
  );
  axilite_interconnect2_32x32 interconnect_0 (
    .S_AXI_aw_ready      (_interconnect_S_AXI_aw_ready),
    .S_AXI_aw_valid      (_master_M_AXI_AWVALID),
    .S_AXI_aw_bits_addr  (_master_M_AXI_AWADDR),
    .S_AXI_w_ready       (_interconnect_S_AXI_w_ready),
    .S_AXI_w_valid       (_master_M_AXI_WVALID),
    .S_AXI_w_bits_data   (_master_M_AXI_WDATA),
    .S_AXI_b_ready       (_master_M_AXI_BREADY),
    .S_AXI_b_valid       (_interconnect_S_AXI_b_valid),
    .S_AXI_b_bits_resp   (_interconnect_S_AXI_b_bits_resp),
    .S_AXI_ar_ready      (_interconnect_S_AXI_ar_ready),
    .S_AXI_ar_valid      (_master_M_AXI_ARVALID),
    .S_AXI_ar_bits_addr  (_master_M_AXI_ARADDR),
    .S_AXI_r_ready       (_master_M_AXI_RREADY),
    .S_AXI_r_valid       (_interconnect_S_AXI_r_valid),
    .S_AXI_r_bits_data   (_interconnect_S_AXI_r_bits_data),
    .S_AXI_r_bits_resp   (_interconnect_S_AXI_r_bits_resp),
    .M0_AXI_aw_ready     (_slave1_S_AXI_AWREADY),
    .M0_AXI_aw_valid     (_interconnect_M0_AXI_aw_valid),
    .M0_AXI_aw_bits_addr (_interconnect_M0_AXI_aw_bits_addr),
    .M0_AXI_w_ready      (_slave1_S_AXI_WREADY),
    .M0_AXI_w_valid      (_interconnect_M0_AXI_w_valid),
    .M0_AXI_w_bits_data  (_interconnect_M0_AXI_w_bits_data),
    .M0_AXI_b_ready      (_interconnect_M0_AXI_b_ready),
    .M0_AXI_b_valid      (_slave1_S_AXI_BVALID),
    .M0_AXI_b_bits_resp  (_slave1_S_AXI_BRESP),
    .M0_AXI_ar_ready     (_slave1_S_AXI_ARREADY),
    .M0_AXI_ar_valid     (_interconnect_M0_AXI_ar_valid),
    .M0_AXI_ar_bits_addr (_interconnect_M0_AXI_ar_bits_addr),
    .M0_AXI_r_ready      (_interconnect_M0_AXI_r_ready),
    .M0_AXI_r_valid      (_slave1_S_AXI_RVALID),
    .M0_AXI_r_bits_data  (_slave1_S_AXI_RDATA),
    .M0_AXI_r_bits_resp  (_slave1_S_AXI_RRESP),
    .M1_AXI_aw_ready     (_lite2fullBridge_S_AXI_aw_ready),
    .M1_AXI_aw_valid     (_interconnect_M1_AXI_aw_valid),
    .M1_AXI_aw_bits_addr (_interconnect_M1_AXI_aw_bits_addr),
    .M1_AXI_w_ready      (_lite2fullBridge_S_AXI_w_ready),
    .M1_AXI_w_valid      (_interconnect_M1_AXI_w_valid),
    .M1_AXI_w_bits_data  (_interconnect_M1_AXI_w_bits_data),
    .M1_AXI_b_ready      (_interconnect_M1_AXI_b_ready),
    .M1_AXI_b_valid      (_lite2fullBridge_S_AXI_b_valid),
    .M1_AXI_b_bits_resp  (_lite2fullBridge_S_AXI_b_bits_resp),
    .M1_AXI_ar_ready     (_lite2fullBridge_S_AXI_ar_ready),
    .M1_AXI_ar_valid     (_interconnect_M1_AXI_ar_valid),
    .M1_AXI_ar_bits_addr (_interconnect_M1_AXI_ar_bits_addr),
    .M1_AXI_r_ready      (_interconnect_M1_AXI_r_ready),
    .M1_AXI_r_valid      (_lite2fullBridge_S_AXI_r_valid),
    .M1_AXI_r_bits_data  (_lite2fullBridge_S_AXI_r_bits_data),
    .M1_AXI_r_bits_resp  (_lite2fullBridge_S_AXI_r_bits_resp)
  );
  axilite_slave_mmap_32x32_r4 slave1 (
    .clock         (clock),
    .reset         (reset),
    .S_AXI_AWADDR  (_interconnect_M0_AXI_aw_bits_addr),
    .S_AXI_AWVALID (_interconnect_M0_AXI_aw_valid),
    .S_AXI_AWREADY (_slave1_S_AXI_AWREADY),
    .S_AXI_WDATA   (_interconnect_M0_AXI_w_bits_data),
    .S_AXI_WVALID  (_interconnect_M0_AXI_w_valid),
    .S_AXI_WREADY  (_slave1_S_AXI_WREADY),
    .S_AXI_BRESP   (_slave1_S_AXI_BRESP),
    .S_AXI_BVALID  (_slave1_S_AXI_BVALID),
    .S_AXI_BREADY  (_interconnect_M0_AXI_b_ready),
    .S_AXI_ARADDR  (_interconnect_M0_AXI_ar_bits_addr),
    .S_AXI_ARVALID (_interconnect_M0_AXI_ar_valid),
    .S_AXI_ARREADY (_slave1_S_AXI_ARREADY),
    .S_AXI_RDATA   (_slave1_S_AXI_RDATA),
    .S_AXI_RRESP   (_slave1_S_AXI_RRESP),
    .S_AXI_RVALID  (_slave1_S_AXI_RVALID),
    .S_AXI_RREADY  (_interconnect_M0_AXI_r_ready)
  );
  axifull_slave_ram_32x32_i4_u1_s8_b131072 slave2 (
    .clock         (clock),
    .reset         (reset),
    .S_AXI_AWADDR  (_lite2fullBridge_M_AXI_aw_bits_addr),
    .S_AXI_AWVALID (_lite2fullBridge_M_AXI_aw_valid),
    .S_AXI_AWREADY (_slave2_S_AXI_AWREADY),
    .S_AXI_WDATA   (_lite2fullBridge_M_AXI_w_bits_data),
    .S_AXI_WVALID  (_lite2fullBridge_M_AXI_w_valid),
    .S_AXI_WREADY  (_slave2_S_AXI_WREADY),
    .S_AXI_BREADY  (_lite2fullBridge_M_AXI_b_ready),
    .S_AXI_BRESP   (_slave2_S_AXI_BRESP),
    .S_AXI_BVALID  (_slave2_S_AXI_BVALID),
    .S_AXI_ARADDR  (_lite2fullBridge_M_AXI_ar_bits_addr),
    .S_AXI_ARVALID (_lite2fullBridge_M_AXI_ar_valid),
    .S_AXI_ARREADY (_slave2_S_AXI_ARREADY),
    .S_AXI_RREADY  (_lite2fullBridge_M_AXI_r_ready),
    .S_AXI_RDATA   (_slave2_S_AXI_RDATA),
    .S_AXI_RRESP   (_slave2_S_AXI_RRESP),
    .S_AXI_RVALID  (_slave2_S_AXI_RVALID)
  );
  assign R_DATA = read_data_reg;
  assign R_DONE = _master_R_DONE;
endmodule

