`timescale 1ns / 1ps
// Generated by CIRCT firtool-1.62.1-1-gdf5ed6ea5
module axilite_master_rw_32x32(
  input         clock,
                reset,
  output [31:0] M_AXI_AWADDR,
  output [2:0]  M_AXI_AWPROT,
  output        M_AXI_AWVALID,
  input         M_AXI_AWREADY,
  output [31:0] M_AXI_WDATA,
  output [3:0]  M_AXI_WSTRB,
  output        M_AXI_WVALID,
  input         M_AXI_WREADY,
  input  [1:0]  M_AXI_BRESP,
  input         M_AXI_BVALID,
  output        M_AXI_BREADY,
  output [31:0] M_AXI_ARADDR,
  output [2:0]  M_AXI_ARPROT,
  output        M_AXI_ARVALID,
  input         M_AXI_ARREADY,
  input  [31:0] M_AXI_RDATA,
  input  [1:0]  M_AXI_RRESP,
  input         M_AXI_RVALID,
  output        M_AXI_RREADY,
  input  [31:0] W_DATA,
                W_ADDR,
  input         W_EN,
  output        W_DONE,
  output [1:0]  W_RESP,
  output [31:0] R_DATA,
  input  [31:0] R_ADDR,
  input         R_EN,
  output        R_DONE,
  output [1:0]  R_RESP,
  output        BUSY
);

  reg  [2:0]  state;
  reg  [31:0] axi_awaddr;
  reg         axi_awvalid;
  reg  [31:0] axi_wdata;
  reg         axi_wvalid;
  reg         axi_bready;
  reg  [31:0] axi_araddr;
  reg         axi_arvalid;
  reg         axi_rready;
  wire        _GEN = state == 3'h0;
  wire        _GEN_0 = state == 3'h1;
  wire        _GEN_1 = state == 3'h2;
  wire        _GEN_2 = state == 3'h3;
  wire        _GEN_3 = _GEN_2 & M_AXI_BVALID;
  wire        _GEN_4 = _GEN | _GEN_0 | _GEN_1;
  wire        _GEN_5 = state == 3'h4;
  wire        _GEN_6 = state == 3'h5;
  wire        _GEN_7 = _GEN_6 & M_AXI_RVALID;
  reg  [2:0]  casez_tmp;
  wire [2:0]  _GEN_8 = _GEN_7 ? 3'h0 : state;
  always_comb begin
    casez (state)
      3'b000:
        casez_tmp = W_EN ? 3'h1 : R_EN ? 3'h4 : state;
      3'b001:
        casez_tmp = M_AXI_AWREADY ? 3'h2 : state;
      3'b010:
        casez_tmp = M_AXI_WREADY ? 3'h3 : state;
      3'b011:
        casez_tmp = M_AXI_BVALID ? 3'h0 : state;
      3'b100:
        casez_tmp = M_AXI_ARREADY ? 3'h5 : state;
      3'b101:
        casez_tmp = _GEN_8;
      3'b110:
        casez_tmp = _GEN_8;
      default:
        casez_tmp = _GEN_8;
    endcase
  end // always_comb
  wire        _GEN_9 = _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_5;
  wire        _GEN_10 = _GEN_0 | _GEN_1 | _GEN_2;
  always @(posedge clock) begin
    if (reset) begin
      state <= 3'h0;
      axi_awaddr <= 32'h0;
      axi_awvalid <= 1'h0;
      axi_wdata <= 32'h0;
      axi_wvalid <= 1'h0;
      axi_bready <= 1'h0;
      axi_araddr <= 32'h0;
      axi_arvalid <= 1'h0;
      axi_rready <= 1'h0;
    end
    else begin
      state <= casez_tmp;
      if (_GEN & W_EN) begin
        axi_awaddr <= W_ADDR;
        axi_wdata <= W_DATA;
      end
      if (_GEN) begin
        axi_awvalid <= W_EN;
        axi_arvalid <= ~W_EN & R_EN;
      end
      else begin
        axi_awvalid <= ~(_GEN_0 & M_AXI_AWREADY) & axi_awvalid;
        axi_arvalid <= (_GEN_10 | ~(_GEN_5 & M_AXI_ARREADY)) & axi_arvalid;
      end
      axi_wvalid <=
        ~_GEN
        & (_GEN_0 ? M_AXI_AWREADY | axi_wvalid : ~(_GEN_1 & M_AXI_WREADY) & axi_wvalid);
      axi_bready <=
        ~_GEN
        & (_GEN_0
             ? axi_bready
             : _GEN_1 ? M_AXI_WREADY | axi_bready : ~_GEN_3 & axi_bready);
      if (~_GEN | W_EN | ~R_EN) begin
      end
      else
        axi_araddr <= R_ADDR;
      axi_rready <=
        ~_GEN
        & (_GEN_10
             ? axi_rready
             : _GEN_5 ? M_AXI_ARREADY | axi_rready : ~_GEN_7 & axi_rready);
    end
  end // always @(posedge)
  assign M_AXI_AWADDR = axi_awaddr;
  assign M_AXI_AWPROT = 3'h0;
  assign M_AXI_AWVALID = axi_awvalid;
  assign M_AXI_WDATA = axi_wdata;
  assign M_AXI_WSTRB = 4'hF;
  assign M_AXI_WVALID = axi_wvalid;
  assign M_AXI_BREADY = axi_bready;
  assign M_AXI_ARADDR = axi_araddr;
  assign M_AXI_ARPROT = 3'h0;
  assign M_AXI_ARVALID = axi_arvalid;
  assign M_AXI_RREADY = axi_rready;
  assign W_DONE = ~_GEN_4 & _GEN_2 & M_AXI_BVALID;
  assign W_RESP = _GEN_4 | ~_GEN_3 ? 2'h0 : M_AXI_BRESP;
  assign R_DATA = M_AXI_RDATA;
  assign R_DONE = ~_GEN_9 & _GEN_6 & M_AXI_RVALID;
  assign R_RESP = _GEN_9 | ~_GEN_7 ? 2'h0 : M_AXI_RRESP;
  assign BUSY = |state;
endmodule

